catalystneuro/neuroconv

- docs/conversion_examples_gallery/imaging/hdf5imaging.rst
- docs/conversion_examples_gallery/imaging/scanbox.rst
- docs/conversion_examples_gallery/imaging/scanimage.rst
- docs/conversion_examples_gallery/imaging/tiff.rst
- docs/conversion_examples_gallery/recording/axona.rst
- docs/conversion_examples_gallery/recording/blackrock.rst
- docs/conversion_examples_gallery/recording/intan.rst
- docs/conversion_examples_gallery/recording/neuralynx.rst
- docs/conversion_examples_gallery/recording/neuroscope.rst
- docs/conversion_examples_gallery/recording/openephys.rst
- docs/conversion_examples_gallery/recording/spikegadgets.rst
- docs/conversion_examples_gallery/recording/spikeglx.rst
- docs/conversion_examples_gallery/sorting/cellexplorer.rst
- docs/conversion_examples_gallery/sorting/kilosort.rst
- docs/conversion_examples_gallery/sorting/neuroscope.rst
- docs/conversion_examples_gallery/sorting/phy.rst
The links stopped working after the most recent porting. This PR restores them.
> Make the links in the conversion gallery work again

- CHANGELOG.md
- src/neuroconv/tools/spikeinterface/__init__.py
- src/neuroconv/tools/spikeinterface/spikeinterface.py
- tests/test_internals/test_si.py
As discussed, I am adding multi segment support to the `write_recording` function. To pin current behavior and increase unittest coverage I am adding the first batch of tests to `add_electrical_series` in `test_si`. The test here are concerned with default arguments and writing the recording to the correct place (e.g. acquisition vs processing). To test the data I also added the option of  writing the data with no iterator but keep the default behavior identical for backward compatibility (it uses "V2").
> Unittest for `add_electrical_series` I

- CHANGELOG.md
- src/neuroconv/tools/yaml_conversion_specification/yaml_conversion_specification.py
- tests/test_on_data/conversion_specifications/GIN_conversion_specification_movies.yml
- tests/test_on_data/test_yaml_conversion_specification.py
When putting together the tutorial for https://github.com/NeurodataWithoutBorders/nwb_hackathons/pull/197, discovered a slight problem specific to the MovieInterface when run through the YAML conversion specification feature.
Tests added.
> [Bug]: Fix file_paths wrapping for YAML specification

- CHANGELOG.md
- tests/test_internals/test_si.py
The other margin was too small as indicated by an error during https://github.com/catalystneuro/neuroconv/pull/33
This PR should fix it.
> Fix overflow memory tests for recorders

- CHANGELOG.md
- src/neuroconv/datainterfaces/ophys/basesegmentationextractorinterface.py
- src/neuroconv/datainterfaces/ophys/caiman/caimandatainterface.py
- src/neuroconv/datainterfaces/ophys/cnmfe/cnmfedatainterface.py
- src/neuroconv/datainterfaces/ophys/extract/extractdatainterface.py
- src/neuroconv/datainterfaces/ophys/suite2p/suite2pdatainterface.py
- src/neuroconv/tools/roiextractors/roiextractors.py
We changed most of the `run_conversion` methods of the base interfaces to have a common signature:
https://github.com/catalystneuro/nwb-conversion-tools/issues/511
Hoever, we left `BaseSegmentationExtractorInterface` and its main method `write_segmentation` without this change. This PR addresses that point. 
This PR is necessary to complete the conversion gallery for the segmentation interfaces with a common interface.
> Add nwb file context to `write_segmentation`

- src/neuroconv/datainterfaces/ecephys/baselfpextractorinterface.py
- src/neuroconv/datainterfaces/ecephys/baserecordingextractorinterface.py
- src/neuroconv/tools/spikeinterface/spikeinterface.py
- tests/test_internals/test_si.py
In #32 non-iterative writing capabilities were added to the electrical series writing pipeline. To keep backwards compatibility the defaults of the function were changed to "v2" which is the "in-house" iterator (coincidentally now the docstrings are right, yei!). However, this change of default parameters was not propagated all the way up to the data interfaces so, in the current state, the would be running non-iterative write by default. This PR addresses this and some other minor refactoring of the `add_electrical_series` that I encountered while re-writing this.
> Propagate default iterator in ecephys to data interfaces

- CHANGELOG.md
- src/neuroconv/datainterfaces/ecephys/axona/axonadatainterface.py
- src/neuroconv/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
- src/neuroconv/datainterfaces/ecephys/openephys/openephysdatainterface.py
- src/neuroconv/datainterfaces/ecephys/spikegadgets/spikegadgetsdatainterface.py
- tests/test_on_data/test_gin_ecephys.py
This PR is to make our tests more centered into spikeinterface. Now all the interfaces have recorders which are spikeinterface BaseRecording objects. This will clean a little bit our `gin_test_ecephys` which before had to take into account for this possibility and should make it easier to pin bugs in the future while also moving forward with the full transition to spikeinterface.
> Old to new recorders refactoring, spikeinterface objects in all recording interfaces

- docs/developer_guide.rst
- docs/developer_guide/contributing.rst
Similar vein to #28, adding a contributing section to the documentation. Largely based on https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst
> Add Contributing section to developer guide

- CHANGELOG.md
- src/neuroconv/datainterfaces/ecephys/ced/ceddatainterface.py
- src/neuroconv/tools/spikeinterface/spikeinterface.py
- tests/test_internals/test_si.py
- tests/test_on_data/test_gin_ecephys.py
I added tests for the `add_electrical_series` function in the spikeinterface module. Also, some change in the code of the module itself. Relevant to the discussion here is the discussion in https://github.com/catalystneuro/neuroconv/issues/34.
> Add unit tests for add  electrical series II (scaling to volts)

- .github/workflows/testing.yml
- docs/api/interfaces.ecephys.rst
- docs/conversion_example_gallery.rst
- docs/conversion_examples_gallery/sorting/neuralynx.rst
- requirements-full.txt
- requirements-minimal.txt
- src/neuroconv/datainterfaces/__init__.py
- src/neuroconv/datainterfaces/ecephys/neuralynx/neuralynxdatainterface.py
- src/neuroconv/tools/spikeinterface/spikeinterface.py
- tests/test_on_data/test_gin_ecephys.py
This should close #16 
Important point. Neuralynx is multi segment. The strategy that I am following for the units table is to concatenate spikes coming from a single unit across multiple segments (appropriately time shifted, https://github.com/SpikeInterface/spikeinterface/pull/865#event-7117106059) and hence pinning to a development branch in spike-interface and the modifications in our own `spikeinterface` module.
> Add data interface for Neuralynx Sorting 

- CHANGELOG.md
- src/neuroconv/tools/spikeinterface/spikeinterface.py
- tests/test_internals/test_si.py
Following on #64 and #37 this PR adds unit tests for the chunking capabilities of `add_electrical_series` and refactors the function  with a separation of the functionality for wrapping the traces in an iterator in a separate function.
> Add unit tests for add electrical series IV (chunking) 

- CHANGELOG.md
- src/neuroconv/datainterfaces/ecephys/axona/axona_utils.py
- src/neuroconv/datainterfaces/ecephys/axona/axonadatainterface.py
- src/neuroconv/tools/spikeinterface/spikeinterface.py
- tests/test_internals/test_si.py
- tests/test_on_data/test_gin_ecephys.py
This PR does two things:
1) Adds spikeinterface supports for the Axona LFP interface.
2) Now that all our of LFP interfaces support spikeinterface the gin tests for LFP can be simplified in the same way as #38 did for the raw recorders.
This forms part of a bigger effort as described on:
#60
> Add spikeinterface support to AxonaLFP 

- CHANGELOG.md
- src/neuroconv/tools/roiextractors/roiextractors.py
While converting some data, I noticed the default name for the optical channels isn't as good as it could be.
So I've updated the default naming of OpticalChannel objects to match the class name.
Also a couple other improvements to default descriptions.
> Update some Imaging default values

- docs/conversion_examples_gallery/recording/abf.rst
- src/neuroconv/datainterfaces/icephys/baseicephysinterface.py
@luiztauffer This prevents the file from getting left around when tests are done.
Also, we standardized the `save_path` argument to `nwbfile_path` among the various tools a while back but I suppose we missed the `neo` one. Added a deprecation warnings for that here as well.
> Fix Icephys gallery

- .github/workflows/update-caches.yml
The full mac workflow has been disabled for some time due to `git-annex` complexities. The full windows workflow has also been touchy over time. Linux is the only platform to never have issues with datalad or git-annex. Caches also cannot effectively be saved on one platform and loaded on another. As such, I've devised an easy workaround.
The workaround uploads the linux cache to an S3 bucket where it can then be downloaded from any arbitrary platform/python version without needing datalad or git-annex.
Took some fiddling around - a couple things to note for future reference...
i) AWS/S3 does not like the lazy symlinks that datalad/GIN leave around when you install a dataset without getting all the file contents. Workflow fails but without any meaningful error if you try to either follow …
> Upload cache to S3 bucket

- CHANGELOG.md
- requirements-full.txt
- requirements-minimal.txt
- src/neuroconv/tools/roiextractors/__init__.py
- src/neuroconv/tools/roiextractors/roiextractors.py
Recent improvements to ROIExtractors altered the behavior of a component of the `write_imaging` method, specifically `add_epochs`.
For the same justification that it was removed in ROIExtractors, this method has always gone untested and unused across the supported formats, and unused in actual conversion projects as well. Epoch information, similar to trials information, is instead typically added via secondary data interfaces that read it from non-imaging files.
> Sync with latest ROIExtractors

- src/neuroconv/tools/nwb_helpers.py
- tests/test_minimal/test_tools.py
Standalone fix peeled from #117 - an issue was discovered when an error was raised *during* the context (not in the enter/exit) for making or loading NWBFiles where the success statement would print prior to the traceback.
This fixes the issue and added an explicit test for it.
> [Bug fix]: Context output during raised error

- .github/workflows/testing.yml
- tests/imports.py
As discussed [previously](https://github.com/catalystneuro/neuroconv/pull/124#issuecomment-1233244770) it would be better if the import tests emulated as much as possible a fresh environment. By that I mean what you get when you run **only** `import neuroconv` or `from neuroconv import tools`, etc. This PR addresses this is in the simplest way I could think off.  One of the problems to solve was that pytest runs all the tests sharing the same process so the attributes of the module are path dependent (i.e. they change according to the point in which the test is run among all the other tests) which is messy when running the full testing suit. 
This PR addresses this by running each of the import tests as independent pytest process and relies on a non-standard name to avoid being called …
> Run import tests as if they were in a fresh environment 

- CHANGELOG.md
- src/neuroconv/datainterfaces/ecephys/requirements.txt
- src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
- tests/test_on_data/test_metadata/test_spikeglx_metadata.py
Bump `spikeinterface` version to `0.95.1` to fix issue with probe annotations `KeyError` for "imDatPrb_type". This ought to resolve #127, an issue also described at https://github.com/SpikeInterface/spikeinterface/issues/923 which is fixed in `0.95.1.`
```
Show here how to reproduce the new behavior (can be a bug fix or a new feature)
```
> Bump `spikeinterface` version to `0.95.1` or higher

- src/neuroconv/tools/roiextractors/roiextractors.py
This PR removes an unecessary call to `get_roi_locations` on the segmentation pipeline. This is called early and in fact unecessarily when `include_roi_centroids` is True as it is called again and used only in that case.
> Remove unnecessary call to `get_roi_locations` in segmentation pipeline

- src/neuroconv/datainterfaces/ophys/requirements.txt
In advance of the upcoming latest NeuroConv release, testing against latest ROIExtractors release.
@h-mayorquin had mentioned something about seeing some errors but it worked fine when I tried, see what the CI says.
> Bump/test ROIExtractors latest release

- docs/api/interfaces.behavior.rst
- docs/conversion_examples_gallery/behavior/sleap.rst
- docs/conversion_examples_gallery/conversion_example_gallery.rst
- src/neuroconv/datainterfaces/behavior/sleap/sleapdatainterface.py
- tests/imports.py
Adds the upcoming sleap data interface to the conversion gallery and documentation API. This should come after #160.
> Add SLEAP conversion gallery example

- docs/conversion_examples_gallery/recording/spikeglx.rst
- src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
Simple PR. This should allow a simpler attachment of the timezone property to the metadata.
> Spikeglx to use datetime object in metadata

- CHANGELOG.md
- src/neuroconv/datainterfaces/ecephys/neuralynx/neuralynxdatainterface.py
- tests/test_on_data/test_gin_ecephys.py
With this PR we drop support for spikextractor backend support for NeuralynxRecordingInterface. The reason for this is that the old backend does not support multi segment extractor. Plus, this should should make #170 way more simple to implement. I still need to add tests for multi segment neuralynx data but this is a simplifying step into that direction.
> Drop spikeextractor backend support for NeuralynxRecordingInterface

- .github/workflows/update-caches.yml
These files aren't needed for our testing purposes with the S3 copy of the data, and since the AWS CLI recursive inclusion/exclusion rules are so tricky, it's easier to just remove them prior to sync to reduce the number of billed requests (and storage space, but that's a way smaller amount).
> Remove unneeded GIN files on S3 copy

- .github/workflows/deploy-tests.yml
Noticed this one on PyNWB and thought it might be useful given how heavy our tests are. When there's a new push to a PR where the tests of a previous push were running, this will automatically cancel them. I kind of do this already myself when I need to free up resources (or avoid feeling bad about the cost to the environment) but it's a bit annoying to do it manually.
> Auto-cancel previous workflow runs

- CHANGELOG.md
- src/neuroconv/datainterfaces/behavior/movie/movie_utils.py
- src/neuroconv/datainterfaces/behavior/movie/moviedatainterface.py
- tests/test_behavior/test_movie_interface.py
While working in the current conversion with Murthy I am facing with some rather large video files and stubbing is very useful for fast iteration. However,  the timestamps themselves are not stubbed and OpenCV goes frame by frame through the whole video rendering the stubbing process useless (even in `external_mode=True`). This PR implements stubbing in the timestamp extraction as well limiting the frame reading in OpenCV.
I added a test and tested this on the Murthy conversion.
> stub Movie interface timestamps

- .github/workflows/assess-file-changes.yml
- .github/workflows/deploy-tests.yml
- CHANGELOG.md
Inspired by #184 for detecting if the `CHANGELOG.md` file was updated automatically, solving the case where both PR-submitter and PR-reviewer forget to check for that.
Already in use on the Fee lab: https://github.com/catalystneuro/fee-lab-to-nwb/pull/41
Also updating some lines related to setting of GitHub action environment variables, which is in a deprecating warning cycle from the old version (red text here) to the new version (green text here).
> Changelog Detector

- CHANGELOG.md
- tests/test_minimal/test_tools.py
A part of our helper functions for running a fully automated transfer+conversion+upload workflow is a one-liner for an automatic dandi upload (given the api token is set as an environment variable). This goes to https://gui-staging.dandiarchive.org/dandiset/200560/draft/files?location=sub-foo, which I just noticed has a `None` as the session ID. So this sets it to be a bit clearer.
> Include session_id in automatic dandi upload test

- CHANGELOG.md
- src/neuroconv/datainterfaces/behavior/video/videodatainterface.py
- tests/test_behavior/test_video_interface.py
For the conversion that I am working on (Murthy) I am transforming multiple videos. Their timestamps are 60 fps but when estimated with our `calculate_regular_series_rate` the estimate becomes 60.0000001 which is unequal to the 60 that the video context is extracting (the correct one). This raises a warning and stores the rate as 60.00001 which is an inaccuracy that arises from our floating point estimate. 
This PR solves this problem for by making the comparison with the estimated rates rounded to two decimals. Standard constant frame rate formats don't meaningfully differ by that amount. 
Also, I realized that the `VideoInterface` was using `DataChunkIterator` even when the conversion option `chunk_data` was False. I changed that.
> Amend rate and fps warning in video interface

- CHANGELOG.md
- docs/conversion_examples_gallery/conversion_example_gallery.rst
- docs/conversion_examples_gallery/recording/plexon.rst
- src/neuroconv/datainterfaces/__init__.py
- src/neuroconv/datainterfaces/ecephys/plexon/plexondatainterface.py
- tests/test_on_data/test_gin_ecephys.py
fix #204 
Adding a PlexonRecordingInterface.
Only the 3rd file in the GIN repo has a recording stream: https://gin.g-node.org/NeuralEnsemble/ephy_testing_data/src/master/plexon
The rest seem to focus on storing the data as waveforms; once Alessio opens up his PR for `write_waveforms` we may want to consider adding `WaveformInterfaces` for the formats that support that data structure.
The header is Intan-like and does not have much extra beyond typical channel properties. Also no session start time.
Example output file: [PlexonRecordingInterface_plexon_recording.zip](https://github.com/catalystneuro/neuroconv/files/10077579/PlexonRecordingInterface_plexon_recording.zip)
Test on GIN data added.
Have to temporarily disable round-trip SI test since [this …
> Add PlexonRecordingInterface

- CHANGELOG.md
- src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglx_utils.py
- src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
I am working on converting data from https://datadryad.org/stash/dataset/doi:10.5061%2Fdryad.d2547d840
It looks like the date of data collection was removed from the data. This is commonly done to protect the anonymity of medical patients.
> Spikeglx parse date

- CHANGELOG.md
- src/neuroconv/datainterfaces/behavior/deeplabcut/requirements.txt
Latest release of `deeplabcut` (yesterday) made `tensorflow` an extra dependency - while this is overall a good thing, since we don't need it at all for `dlc2nwb`, they haven't yet released the version of `dlc2nwb` which [contains a safer import](https://github.com/DeepLabCut/DLC2NWB/blob/main/dlc2nwb/utils.py#L16-L17) of the DLC package (though at the loss of recording the version provenance, it seems...)
I'll ask them to cut a new release and once they do I'll just replace this temporary addition with the up-pin on `dlc2nwb`. But for now, tests are breaking due to DLC attempting to import the uninstalled dependency: https://github.com/catalystneuro/neuroconv/actions/runs/3769847940/jobs/6409325021
> Fix DLC tests (from 12/23/2022 release)

- .github/workflows/testing.yml
- CHANGELOG.md
Working on spikeinterface  I realized that the version that we have here is going to be depreacted (actually it says that it should be deprecated already!):
https://github.com/codecov/codecov-action
> Update code coverage action version

- .github/workflows/deploy-tests.yml
Copycatting @h-mayorquin to replace a functionality that used to be an external workflow but now can be done internal to all GitHub actions
Testing it out here
> Swap CI to concurrency

- CHANGELOG.md
- src/neuroconv/schemas/yaml_conversion_specification_schema.json
- src/neuroconv/tools/yaml_conversion_specification/yaml_conversion_specification.py
- tests/test_on_data/conversion_specifications/GIN_conversion_specification.yml
- tests/test_on_data/conversion_specifications/GIN_conversion_specification_missing_nwbfile_names.yml
- tests/test_on_data/conversion_specifications/GIN_conversion_specification_no_nwbfile_name_or_other_metadata.yml
Generally, if you want a conversion to be a stub_test, you want this for every session and every data interface, so I've added an option of global conversion options where this can be specified. Any conversion option specified here propagates to all sessions and data interfaces. You can still specify conversion_options on a session and interface level if you want to
> [YAML]: allow a global conversion_options

- CHANGELOG.md
- src/neuroconv/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
This PR deletes some automated BlackRock behavior that put certain ns files in processing rather than acquisition. I don't think the automated decision making was necessarily right and the user can use the "write_as" arg to control that manually.
> simplify blackrockdatainterface.py

- .github/workflows/deploy-tests.yml
Since we essentially only ask for changelog updates when source code is changed, might as well prevent it from triggering otherwise?
> Changlog CI trigger on source changes only

- tests/test_minimal/test_tools/test_dandi_transfer_tools.py
CI breaking again due to failure on DANDI server
Good to catch so we can warn them and get a fix ASAP
But for years this test has run without hardly ever causing issues, wonder what's been going on lately
> Disable DANDI test temporarily (again)

- src/neuroconv/datainterfaces/ecephys/baserecordingextractorinterface.py
- src/neuroconv/tools/spikeinterface/spikeinterface.py
I was using `RecordingInterface.run_conversion` and it was not clear to me from the docstring how to turn on a progress bar. This expands the docstring in two places to make this explicit.
> expand iterator_opts in docstrings to include all args

- docs/catalogue/catalogue.rst
It works in the browser, but external link CI complains about it being forbidden; seeing if this works
> try to fix external link for ahrens paper

- requirements-minimal.txt
Testing a fix that was just revealed by failing tests on #428; zero clue why it happened this way, the [daily tests ran perfectly find 6 hours earlier](https://github.com/catalystneuro/neuroconv/actions/runs/4863353553/jobs/8670942626), and the only major difference I can spot between the two CI installations is the numpy version was 1 patch lower in the dailies.
> Set upper numpy bound for Python < 3.11

- CHANGELOG.md
- docs/conversion_examples_gallery/recording/openephys.rst
- src/neuroconv/datainterfaces/__init__.py
- src/neuroconv/datainterfaces/ecephys/openephys/openephysbinarydatainterface.py
- src/neuroconv/datainterfaces/ecephys/openephys/openephysdatainterface.py
- src/neuroconv/datainterfaces/ecephys/openephys/openephyslegacydatainterface.py
- src/neuroconv/datainterfaces/ecephys/openephys/openephyssortingdatainterface.py
- tests/test_on_data/test_gin_ecephys/test_openephys.py
- tests/test_on_data/test_gin_ecephys/test_openephyslegacy.py
- tests/test_on_data/test_recording_interfaces.py
fix #426 
The multi-stream `OpenEphysConverter` will be added in a follow-up as this is more than enough for a single PR
While I was poking around in these interfaces for the first time in a while, I made some other changes.
- Enhanced the tests a bit (the folder structure one was because of a new issue if you're not careful about the path in the new testing data)
- Suppressed the annoying print statements from `pyopenephys` during metadata collection
- Moved the sorting interface since I'm not sure why it was still in the recording interface file
> Add stream control to OpenEphysBinary

- .github/workflows/auto-publish.yml
- pyproject.toml
While looking at the configuration for Buzsaki I realized this one is outdated. I also increase the range of black so that it allows code for python3.8 onwards.
> Update publish action 

- CHANGELOG.md
- src/neuroconv/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py
There are two functions that extract proeprties for the recording extractor on Neuroscope.
1. `subset_shank_channels` which takes a subset of the channels that are anatomically relevant according to the docstring.
2. `add_recording_extractor_properties` which uses the properties of the XML to add other properties such as shank electrode number and group memebership.
The problem right now is that they are in different order in `NeuroScopeLFPInterface` and in `NeuroScopeRecordingInterface` which leads to them having inconsistent properties when both of them are added in a conversion.
This PR fixes this by having them perform exactly the same operation.
> Align recording extractor properties between Neuroscope raw and LFP

- CHANGELOG.md
- src/neuroconv/basetemporalalignmentinterface.py
- src/neuroconv/datainterfaces/behavior/audio/audiointerface.py
- src/neuroconv/datainterfaces/behavior/deeplabcut/deeplabcutdatainterface.py
- src/neuroconv/datainterfaces/behavior/sleap/sleapdatainterface.py
- src/neuroconv/datainterfaces/behavior/video/videodatainterface.py
- src/neuroconv/datainterfaces/ecephys/baserecordingextractorinterface.py
- src/neuroconv/datainterfaces/ecephys/basesortingextractorinterface.py
- src/neuroconv/datainterfaces/icephys/abf/abfdatainterface.py
- src/neuroconv/datainterfaces/icephys/baseicephysinterface.py
- src/neuroconv/datainterfaces/ophys/baseimagingextractorinterface.py
- src/neuroconv/datainterfaces/ophys/basesegmentationextractorinterface.py
- src/neuroconv/datainterfaces/text/timeintervalsinterface.py
- src/neuroconv/tools/testing/data_interface_mixins.py
- src/neuroconv/tools/testing/mock_interfaces.py
- tests/test_behavior/test_audio_interface.py
- tests/test_behavior/test_video_interface.py
- tests/test_minimal/test_converter.py
- tests/test_on_data/test_behavior_interfaces.py
- tests/test_on_data/test_gin_behavior.py
- tests/test_on_data/test_gin_icephys.py
- tests/test_on_data/test_temporal_alignment/test_temporal_alignment_methods.py
fix #301 
Various cleanups around the repo to bring things up to the current standard for temporal alignment related methods and tests
Also adjusting the final naming conventions for the few methods that are simple setters as opposed to those that perform actual operations
On that note, I did notice that `align_starting_time` and `align_segment_starting_times` do actually perform operations on the underlying objects in the majority of cases so they aren't strictly setters; special cases include icephys, sorters without recordings attached, and sometimes video; but since it always has the possibility of being an operation as opposed to a strict setter 
As such it is only the `timestamps` notion that has setters and getters as methods referencing some type of underlying property
> [Sync VIIc] Final alignment cleanup and name changes

- src/neuroconv/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py
Looks like an update to Codespell caught a typo!
> Fix docstring typo

- src/neuroconv/schemas/base_metadata_schema.json
partial fix for https://github.com/NeurodataWithoutBorders/nwb-guide/issues/229
The GUIDE inherits that aspect all the way from the NeuroConv base schema
> remove default placeholder for subject description

- src/neuroconv/datainterfaces/ecephys/edf/requirements.txt
CI has been failing on Python 3.11 over the weekend, seeing if this fixes it
Specifically it's an import problem through numpy caused by EDF lib
> pin upper bound on EDF lib numpy

- CHANGELOG.md
- src/neuroconv/datainterfaces/ecephys/neuroscope/neuroscope_utils.py
- src/neuroconv/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py
I was discussing with @CodyCBakerPhD today about the logic of these functions as I wanted to have more explicit docstrings to indicate what they do. I have been working on a conversion that uses Neuroscope and thinking on how to best add metadata. I think this is useful to me and future developers that will need to read these functions to understand what they do.
> Add docstrings for filtering out non-neural channel functions in Neuroscope Interface

- src/neuroconv/datainterfaces/ecephys/cellexplorer/cellexplorerdatainterface.py
As stated in the title. Probably left there after we droped spike extractor.
> Remove oudated warning from CellExplorerSortingInterface

- CHANGELOG.md
- src/neuroconv/datainterfaces/ecephys/cellexplorer/cellexplorerdatainterface.py
As mentioned before, in the new CellExplorer format the sampling frequency is the in the same file where the spikes are. I made the changes in spikeinterface to take this into account https://github.com/SpikeInterface/spikeinterface/pull/1628 but we won't have a release in a while.
Meanwhile, we will need this temporary change to the interface so we can use it in the current conversions.
> `CellExplorerSortingInterface` to get sampling frequency from new CellExplorer format

- CHANGELOG.md
- src/neuroconv/tools/spikeinterface/spikeinterface.py
I have a memory overflow error that is killing my full conversion for some sessions when working on this https://github.com/catalystneuro/buzsaki-lab-to-nwb/pull/66.
I am tracking down the issue and one of the things I noticed is that for very long-recordings extracting the timestamps in `add_electrical_series (to check if they are regular) create a large memory allocation. For example, for the 5 hours long recordings of some sessions the timestamps are ~ 2 GiB. We should avoid that if possible.
On the other hand, when the recording objects in spikeinterface do not have time vectors the call to `get_times` just creates artificial timestamps using the sampling rate which are regular by creation. As our interest is to check whether the timestamps are regular or not this is redundant and …
> Avoid redundant timestamp creation in `add_electrical_series` for recording objects without time vector

- .github/workflows/dev-testing.yml
- .github/workflows/formatwise-installation-testing.yml
- .github/workflows/testing.yml
- CHANGELOG.md
- src/neuroconv/datainterfaces/__init__.py
- src/neuroconv/datainterfaces/ecephys/cellexplorer/cellexplorerdatainterface.py
- src/neuroconv/datainterfaces/ecephys/cellexplorer/requirements.txt
- src/neuroconv/tools/testing/data_interface_mixins.py
- tests/test_on_data/test_recording_interfaces.py
OK, after working on https://github.com/catalystneuro/neuroconv/pull/488 I realized that we have already a Binary recorder that can be used directly to load the binary files. This, coupled with the information in the new `session.mat` of CellExplorer is all we need to build this extractor.
This should work for both adding the metadata and also the raw data and lfp for which we usually use the Neuroscope interface so we don't need to duplicate interfaces:
> Add `CellExplorerRecordingInterface` 

- CHANGELOG.md
- src/neuroconv/datainterfaces/ecephys/baselfpextractorinterface.py
- src/neuroconv/datainterfaces/ecephys/baserecordingextractorinterface.py
Just discovered after examining some more recent outputs shared by @h-mayorquin that default compression for recording interfaces (maybe others too) had been disabled by mistake with #455 
While the eventual goal of #475 is to set the signature to `None` as it is seen here, the default behavior in that case is still to apply GZIP by default using the default backend of HDF5, with the 'disable' override being done a slightly different way
> hotfix default gzip for recordings

- src/neuroconv/datainterfaces/ecephys/basesortingextractorinterface.py
- src/neuroconv/datainterfaces/ecephys/cellexplorer/cellexplorerdatainterface.py
- tests/test_on_data/test_sorting_interfaces.py
This is another option to avoid the creation of an unecessary large time vector for the dummy sorting. 
This probably is telling that we need a lazy mechanism to handle timestamps in spikeinterface. I am thinking about how to do this.
Has #494 as a base.
> Add ecephys metadata to `CellExplorerSorting` through method

- tests/test_on_data/test_recording_interfaces.py
Daily CI just caught an error caused by the latest release of `jsonschema` (7 hours ago) finding a mistake in a test case
Should be simple fix
> [Bug] fix test schema definition

- .github/workflows/deploy-tests.yml
- .github/workflows/dev-testing.yml
- src/neuroconv/datainterfaces/ophys/requirements.txt
Latest release of ROIExtractors split the BrukerTifExtractor into distinct categories (multi-channel, multi-plane, volumetric) that can't be automatically routed through a common class; so the current interface only works using the previous version of ROIExtractors
https://github.com/catalystneuro/neuroconv/pull/507 will loosen this pin as a part of its expansion
> Pin ROIExtractors temporarily

- CHANGELOG.md
- setup.py
- src/neuroconv/datainterfaces/ecephys/spike2/spike2datainterface.py
- src/neuroconv/tools/importing.py
As discovered by @rly on https://github.com/NeurodataWithoutBorders/nwb-guide/issues/354, despite the fact that neuroconv as a package works fine due to our previous lazy interface + exclusion principles at the interface level, it still attempts to install it (even seems to grab some files from the PyPI package) but fails at a point during the environment build process
This excludes it entirely from being bundled with NeuroConv in this situation
Also some docstring improvements
Unfortunately no way to test this in CI
> Improve sonpy installation for M1 Mac

- CHANGELOG.md
- src/neuroconv/datainterfaces/ecephys/basesortingextractorinterface.py
Again related to the multiplication by 1.1 in `subset_sorting` in [this line](https://github.com/catalystneuro/neuroconv/blob/main/src/neuroconv/datainterfaces/ecephys/basesortingextractorinterface.py#L225). The resulting `end_frame` can be a non-integer. In SpikeInterface, non-integer `end_frame`s are truncated to int in `FrameSliceRecording` [here](https://github.com/SpikeInterface/spikeinterface/blob/main/src/spikeinterface/core/frameslicerecording.py#L54) but left unchanged in `FrameSliceSorting` [here](https://github.com/SpikeInterface/spikeinterface/blob/main/src/spikeinterface/core/frameslicesorting.py#L79). Since data are sliced based on frames being `< end_frame`, this means the recording excludes `int(end_frame)` while the sorting includes `int(end_frame)`. Only a problem if …
> Fix `subset_sorting` behavior by explicitly casting non-integer `end_frame` to int

- .github/workflows/dailies.yml
- .github/workflows/test-external-links.yml
Turns out I haven't been getting the native GitHub notifications for daily failures, similar to what happened on the NWB Inspector a while back
This should fix it
Happy to add anyone else that wants to the email list
> Daily email notification for failures

- src/neuroconv/datainterfaces/behavior/deeplabcut/requirements.txt
Tests on `main` failed yesterday due to a new release of https://pypi.org/project/tables/#history which causes a dependency conflict with blosc2 on Python 3.8
> [Bug] Split tables requirements across versions

- docs/user_guide/temporal_alignment.rst
Missing a self parameter in some code of the gallery.
> Fix small typo temporal aliginment docs

- CHANGELOG.md
- src/neuroconv/datainterfaces/behavior/fictrac/fictracdatainterface.py
- src/neuroconv/datainterfaces/behavior/fictrac/requirements.txt
- tests/test_on_data/test_behavior_interfaces.py
When working on the Clandining conversion I realized that the first line of the data header has non-valid values save the timestamp. The timestamp is the unix time epoch in milliseconds which can be used to extract a more complete `session_start_time` as previously we were extracting only the date.
I did some other improvements to the code like adding `starting_time` when they are not zero which were not done before.
> Add complete session start time to FicTrac

- CHANGELOG.md
- src/neuroconv/datainterfaces/__init__.py
- src/neuroconv/datainterfaces/ecephys/spike2/spike2datainterface.py
- tests/test_ecephys/test_ecephys_interfaces.py
- tests/test_on_data/test_gin_ecephys/test_raw_recordings.py
- tests/test_on_data/test_recording_interfaces.py
Came up with @garrettmflynn in the GUIDE. Probably overdue
> Deprecate CED Recording

- CHANGELOG.md
- docs/conversion_examples_gallery/behavior/fictrac.rst
- src/neuroconv/datainterfaces/behavior/fictrac/fictracdatainterface.py
- src/neuroconv/datainterfaces/ecephys/neuroscope/neuroscope_utils.py
- tests/test_on_data/test_behavior_interfaces.py
As discussed with @bendichter last week. Added an extra argument in the `__init__` of the interface called radius which is the radius of the treadmill foam ball in the setup. If provided, the units are converted to actual distances and stored as such.
I also changed the container from Compass to Position as discussed.
> Support adding data in meters in `FicTracDataInterface`

- CHANGELOG.md
- src/neuroconv/datainterfaces/behavior/fictrac/fictracdatainterface.py
- tests/test_on_data/test_behavior_interfaces.py
This was a suggestion from @CodyCBakerPhD in our  last conversion which I think makes sense. We were adding the data scaled which increases the error if the measurement of the radius is not very precise. 
This method keeps both the radius, the right units and the original data without imprecisions. 
I modified the test to account for this.
> Add radius as conversion (scaling) instead of adding the scaled data in `FicTrac`

- CHANGELOG.md
- src/neuroconv/datainterfaces/behavior/fictrac/fictracdatainterface.py
- tests/test_on_data/test_behavior_interfaces.py
Note that this has #619 as a base.
In the context of #608. 
Coercing the timestamps to start from 0 for FicTrac. In this case, the first row was actually a timestamp 0 that was modified by FicTrac logic see here:
https://github.com/rjdmoore/fictrac/issues/29
> Fix FicTrac timestamps. Coerce them to start at 0.

- CHANGELOG.md
- src/neuroconv/datainterfaces/behavior/fictrac/fictracdatainterface.py
- src/neuroconv/datainterfaces/behavior/neuralynx/nvt_utils.py
- tests/test_on_data/test_behavior_interfaces.py
As in the title. The metadata is added as a comment to each of the SpatialSeries. Added a test for this.
Ben suggested to change the parsing function to something along the lines of #580 so I did it here as well
> add configuration metadata to fictrac

- CHANGELOG.md
- src/neuroconv/datainterfaces/behavior/video/video_utils.py
- src/neuroconv/tools/hdmf.py
- src/neuroconv/tools/roiextractors/imagingextractordatachunkiterator.py
- src/neuroconv/tools/roiextractors/roiextractors.py
- src/neuroconv/tools/testing/mock_ttl_signals.py
- tests/test_behavior/test_audio_interface.py
- tests/test_behavior/test_video_utils.py
- tests/test_ophys/test_imagingextractordatachunkiterator.py
- tests/test_ophys/test_tools_roiextractors.py
This is a better alternative to https://github.com/catalystneuro/neuroconv/pull/636 as it fixes a more fundamental issue.
The previous version of GenericDataChunkIterator raises an exception in the case where
* The array has only one dimension and
* The array is large enough to not satisfy the early termination condition
This issue was not being picked up by the tests because the simulated .wav files are not nearly large enough to get passed the early termination condition.
The problematic line was
```
smallest_chunk_axis, second_smallest_chunk_axis, *_ = np.argsort(self.chunk_shape)
```
because in the case of a 1D array, there is no second smallest chunk axis. So with this PR, this case is handled separately.
In terms of verifying that this works properly, I temporarily removed the early …
> Fix GenericDataChunkIterator for large arrays (affects .wav conversion)

- CHANGELOG.md
- src/neuroconv/datainterfaces/ophys/basesegmentationextractorinterface.py
- src/neuroconv/schemas/metadata_schema.json
- src/neuroconv/tools/roiextractors/roiextractors.py
- tests/test_ophys/test_tools_roiextractors.py
Final piece for #601 
Resolve https://github.com/catalystneuro/neuroconv/issues/603
Changes the current metadata schema for `Fluorescence` and `DfOverF` 
- the name of the plane segmentation is used to identify which traces are added to the file. 
- the name of the traces can be changed in the inner schema for the response series metadata (see example below)
Example metadata structure:
```
dict(
Ophys=dict(
Fluorescence=dict(
name="Fluorescence",
PlaneSegmentationChan1Plane0=dict(
raw=dict(name="RoiResponseSeriesChan1Plane0", description="raw fluorescence signal"),
deconvolved=dict(name="DeconvolvedChan1Plane0", description="deconvolved fluorescence signal"),
neuropil=dict(name="NeuropilChan1Plane0", description="neuropil fluorescence signal"),
),
PlaneSegmentationChan1Plane1=dict( …
```
> Change `Fluorescence`/`DFOverF` metadata schema for RoiResponseSeries from `array` type to `object`

- .github/workflows/deploy-tests.yml
- src/neuroconv/tools/data_transfers.py
Replaced `jobs` with the correct variable (`number_of_jobs`) when parsing the user's selection of job count from the GUIDE.
> Fix number_of_jobs parsing

- CHANGELOG.md
- requirements-minimal.txt
- src/neuroconv/tools/path_expansion.py
Over the last week or so I worked with the new dev of the `parse` library to incorporate the datetime parsing into that library: https://github.com/r1chardj0n3s/parse/pull/165. This was the only feature that motivated the splinter of `fparse`, so we can now move our dependence back to `parse` with version >=1.20.0 and archive `fparse`.
There is one small difference in the `parse` implementation, which is that it infers whether the parsed value should be a `datetime`, a `date`, or a `time`. If no time information is present, `parse` returns a `date` object. NeuroConv expects a `datetime`, and I think PyNWB requires a `datetime` for the `session_start_time`, so for backwards compatibility and for better compatibility with PyNWB, I included a line that transforms `date`s to `datetime`s when …
> change from using fparse to using parse

- CHANGELOG.md
- requirements-minimal.txt
- setup.py
- src/neuroconv/tools/__init__.py
- src/neuroconv/tools/data_transfers/__init__.py
- src/neuroconv/tools/data_transfers/_aws.py
- src/neuroconv/tools/data_transfers/_dandi.py
- src/neuroconv/tools/data_transfers/_globus.py
- src/neuroconv/tools/data_transfers/_helpers.py
- src/neuroconv/tools/yaml_conversion_specification/__init__.py
- src/neuroconv/tools/yaml_conversion_specification/_yaml_conversion_specification.py
fix #651 
While I was poking around those helper functions, I reorganized distinct flavor of the data transfer tools into the same style as the backend/dataset config
Note that I'm thinking more and more how we might want to switch to using pyproject.toml soon to avoid implicit magic in our import structure
> Make DANDI optional

- src/neuroconv/basedatainterface.py
- src/neuroconv/datainterfaces/behavior/fictrac/fictracdatainterface.py
- src/neuroconv/datainterfaces/behavior/video/videodatainterface.py
- src/neuroconv/datainterfaces/ecephys/axona/axonadatainterface.py
- src/neuroconv/datainterfaces/ecephys/blackrock/header_tools.py
- src/neuroconv/datainterfaces/ecephys/neuralynx/neuralynxdatainterface.py
- src/neuroconv/datainterfaces/ecephys/neuroscope/neuroscope_utils.py
- src/neuroconv/datainterfaces/ecephys/spikegadgets/spikegadgetsdatainterface.py
- src/neuroconv/datainterfaces/text/timeintervalsinterface.py
- src/neuroconv/nwbconverter.py
- src/neuroconv/tools/data_transfers/_dandi.py
- src/neuroconv/tools/hdmf.py
- src/neuroconv/tools/importing.py
- src/neuroconv/tools/neo/neo.py
- src/neuroconv/tools/nwb_helpers/_configuration_models/_base_dataset_io.py
- src/neuroconv/tools/nwb_helpers/_dataset_configuration.py
- src/neuroconv/tools/roiextractors/roiextractors.py
- src/neuroconv/tools/spikeinterface/spikeinterface.py
- src/neuroconv/tools/testing/data_interface_mixins.py
- src/neuroconv/utils/dict.py
- src/neuroconv/utils/json_schema.py
- tests/imports.py
- tests/test_behavior/test_audio_interface.py
- tests/test_ecephys/test_tools_spikeinterface.py
- tests/test_on_data/test_yaml_conversion_specification.py
- tests/test_ophys/test_tools_roiextractors.py
None of these changes change the functionality of the code. They are all just tidying up a bit.
* remove unused imports
* fix typos
* attributes like `data_interface_cls: BaseSortingExtractorInterface` should be `Type[BaseSortingExtractorInterface]`, indicating that it takes a class, not an object
* fix some typehint annotations
> general cleanup

- CHANGELOG.md
- src/neuroconv/tools/roiextractors/imagingextractordatachunkiterator.py
- tests/test_ophys/test_imagingextractordatachunkiterator.py
- tests/test_ophys/test_tools_roiextractors.py
Detected during review of Clandinin example files; the chunks are way too large since they include all depths (which have a huge number of planes)
Needs tests
> Add depth to ROI iterator

- src/neuroconv/tools/testing/data_interface_mixins.py
This PR makes the dev tests work with the latest changes in SI. 
Context:
@alejoe91 requested to add a new compulsory `t_start` argument in `NWBSortingExtractor`. I the context of spikeinterface this makes sense because we want the spike frames (not the spike times) to be with reference to the first frame in the corresponding acquisition. We did not introduce a default value because we want  users to make that choice explictly.
> Fix sorting tests

- CHANGELOG.md
- src/neuroconv/tools/path_expansion.py
- tests/test_minimal/test_tools/test_expand_paths.py
After #675 @bendichter [mentioned ](https://github.com/catalystneuro/neuroconv/pull/675#issuecomment-1840847452) that we are still missing the case of nested over matching:
> "a_simple_pattern_{session_id}" applied to "tmp/base_directory/a_simple_pattern_2/nested/" will still return session_id="2/nested/" when it should not match
and proposed a solution of excluding metadata entries that have file separators (slashes in posix or double front slashes on windows) from the matches. This PR implements this solution and amends the tests to reflect that.
This should fix #674
> Fix path expander II

- src/neuroconv/tools/spikeinterface/spikeinterface.py
Disables hardcoded `H5DataIO` wrapping in `tools.spikeinterface.write_recording` if `compression=None`.
This change enables one to use the `configure_backend` functionality (added a note in the docstring)
> Disable H5DataIO compression if compression is None

- src/neuroconv/datainterfaces/behavior/sleap/requirements.txt
Recent release of sleap doesn't support Python 3.9 and causes error in CI; not one of our dev test suite packages so didn't catch it until today
> Fix sleap python range

- src/neuroconv/tools/nwb_helpers/_configuration_models/_base_dataset_io.py
- src/neuroconv/tools/nwb_helpers/_dataset_configuration.py
- tests/test_minimal/test_tools/test_backend_and_dataset_configuration/test_helpers/test_configure_backend_defaults.py
Bug caught by @alejoe91 resulting from some odd mutation of the dataset resulting from it being wrapped unnecessarily in a `DataChunkIterator` (@h-mayorquin had good intuition that this might cause a problem and should be avoided; I've reverted to more basic dtype retrieval for that step until we figure out a better path forward; will work fine for source data that are numpy arrays or anything similar)
> [Backend Configuration IIIc]: Improved testing and debugs

- .github/workflows/deploy-tests.yml
- src/neuroconv/datainterfaces/ecephys/requirements.txt
Daily tests on `main` started failing as of SI release `0.100.0`: several hours ago, https://github.com/catalystneuro/neuroconv/actions/runs/7802776510/job/21281012657
Downpinning until fix is pushed separately
> Downpin spikeinterface to fix tests on main

- CHANGELOG.md
- src/neuroconv/datainterfaces/ecephys/baserecordingextractorinterface.py
- tests/test_on_data/test_recording_interfaces.py
As per meeting; moving this from a generic interface method that has no programmatic use to GUIDE specific interactions
> Remove roundabout JSON interaction with electrode table

- docs/api/interfaces.ecephys.rst
> add `AlphaOmega` recording to docs API

- .github/workflows/testing.yml
- requirements-testing.txt
- src/neuroconv/datainterfaces/ophys/scanimage/scanimageimaginginterface.py
- tests/imports.py
Failed to notice this with PR #731, my bad. Imports like this should be lazy and done within the `__init__` of the class so the outer imports don't fail under a minimal installation
> [Bug] Fix non-lazy ROIExtractors import

- CHANGELOG.md
- src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglx_utils.py
- src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
Currently supported SI version range supports automatic probe setting for SpikeGLX
Also moving a spare function to the nearby utilities to live with the other one-off functions
> [Cleanup] SpikeGLXRecording utility and duplicated probe setting

- CHANGELOG.md
- requirements-minimal.txt
- src/neuroconv/datainterfaces/ecephys/axona/axonadatainterface.py
- src/neuroconv/utils/json_schema.py
- tests/test_behavior/test_audio_interface.py
- tests/test_minimal/test_utils/test_json_schema_utils.py
In GUIDE, the we need data entry help text for fields of the interface constructors. See for example:
Without this help field, it is sometimes quite unclear which specific file or folder the user is meant to select. This help text is taken from the "description" field in the source json schema. This particular field for the `SpikeGLXRecordingInterface` was added manually to the source schema:
https://github.com/catalystneuro/neuroconv/blob/f80899b00a3749e5c8c9adf812ca0b69b45e7dd3/src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py#L27-L31
While it is possible to do this with every DataInterface, that would be redundant with the docstring of the init and would add a lot of lines of code.
This PR solves this problem in general by instead taking this description directly …
> get json schema descriptions from docstrings

- src/neuroconv/datainterfaces/ecephys/requirements.txt
From comment https://github.com/catalystneuro/neuroconv/pull/195#issuecomment-1342900752
Trying to loosen this bound as a part of a potential fix to the GUIDE for supporting a PyInstaller hook for Pydantic v2
Testing here to see if the previous issue with the packaging lower bound has been resolved by now
> Try to remove packaging bound

- src/neuroconv/datainterfaces/ophys/baseimagingextractorinterface.py
propagate photon_series_type to get_metadata() in BaseImagingExtractorInterface otherwise it will get default_metadata for just TwoPhotonSeries (not OnePhotonSeries) being the TwoPhotonSeries the default
> propagate photon_series_type to get_metadata

- CHANGELOG.md
- src/neuroconv/tools/spikeinterface/spikeinterface.py
- tests/test_ecephys/test_tools_spikeinterface.py
Related to https://github.com/SpikeInterface/spikeinterface/issues/2588
The mask to find the electrodes corresponding to the electrical series should use both channel names and channel groups, while the current implementation only uses channel names.
Extended the test too, because we were only checking the `nwbfile.electrodes`, not the `es.electrodes`
> Fix writing electrodes field in add_electrical_series

- docs/conf.py
- docs/conversion_examples_gallery/behavior/fictrac.rst
- docs/index.rst
It seems that this will take a bit longer than we expected.
https://github.com/rjdmoore/fictrac/issues/30
I will also remember that there is another broken link.
> add fictract docs to ignore links as it is not working temporarily

- tests/test_on_data/test_behavior_interfaces.py
Replaces #825 because of dodgy commit history issue.
> Path as string in FicTrac test

- .github/workflows/testing.yml
- requirements-minimal.txt
- requirements-testing.txt
Tests just failed today due to a surprise break from Zarr release yesterday - some issue with decoding Blosc for our custom backend configuration stuff
Shouldn't effect actual typical usage of the backend feature aside from Blosc I assume, since none of the other compressor tests complain
[Filed issue with hdmf-zarr](https://github.com/hdmf-dev/hdmf-zarr/issues/192) so team knows about it, and if it's an issue with the way they specify the read from the IO level (I doubt it, but never know)
Downpinning in tests temporarily to fix the CI, will check over time if resolved automagically
> Pin Zarr for tests

- tests/test_minimal/test_tools/test_backend_and_dataset_configuration/test_common_dataset_io_configuration_model.py
Replaces `Union[HDF5DatasetIOConfiguration, ZarrDatasetIOConfiguration]` with `DatasetIOConfiguration`. This doesn't change much, but this is the standard way of specifying multiple subclasses that share a base class, and it readies the repo for additional backends if they should ever come
> use abstract class DatasetIOConfiguration for typing

- .github/workflows/dev-testing.yml
- .github/workflows/doctests.yml
- .github/workflows/formatwise-installation-testing.yml
- .github/workflows/live-service-testing.yml
- .github/workflows/test-external-links.yml
- .github/workflows/testing.yml
- .github/workflows/update-s3-testing-data.yml
- .readthedocs.yaml
- CHANGELOG.md
- setup.py
- src/neuroconv/datainterfaces/ecephys/spike2/requirements.txt
- src/neuroconv/datainterfaces/ecephys/spike2/spike2datainterface.py
- tests/test_on_data/test_recording_interfaces.py
As discussed on https://github.com/catalystneuro/roiextractors/pull/276#discussion_r1463954610.
> Drop python 3.8

- CHANGELOG.md
- src/neuroconv/nwbconverter.py
- src/neuroconv/utils/json_schema.py
- tests/test_on_data/test_gin_ecephys/test_lfp.py
Is that something that we would want? I always find it annoying when working on conversations that I have to stringify at the signature or before.
> Support Path objects in source_data schema validation

- src/neuroconv/tools/spikeinterface/spikeinterface.py
I think that we have a straggler here @CodyCBakerPhD .
> Remove timestamps `H5DataIO`wrapper in `tools.spikeinterface`

- src/neuroconv/tools/nwb_helpers/_configuration_models/_base_backend.py
- src/neuroconv/tools/nwb_helpers/_configure_backend.py
- src/neuroconv/tools/spikeinterface/spikeinterface.py
From the discussion in https://github.com/catalystneuro/neuroconv/pull/816/files#r1607028944 from #816
OK, this is I think a simpler approach. breaks the previous construction into two functions. The first part finds all the locations that require-remapping and the second part uses pydantic machinery to create a copy of the model and modify only what requires modification.
I think this should be faster and is more flexible. What would be missing is some testing. Let me know what you think.
> Avoid double computation for backend check

- CHANGELOG.md
- src/neuroconv/tools/spikeinterface/spikeinterface.py
- tests/test_ecephys/test_tools_spikeinterface.py
This was missing. Added a test.
I will add the analogous for `add_electrode` in another PR.
> Add support for double ragged property in `add_units_table`

- CHANGELOG.md
- src/neuroconv/basedatainterface.py
- src/neuroconv/nwbconverter.py
- tests/test_ecephys/test_mock_nidq_interface.py
attn @garrettmflynn 
Can you give this a try for https://github.com/NeurodataWithoutBorders/nwb-guide/pull/821?
> [Bug] Pass customized backend to run_conversion

- docs/user_guide/backend_configuration.rst
Reading this page over again, I feel the first section, [Default configuration](https://neuroconv.readthedocs.io/en/main/user_guide/backend_configuration.html#default-configuration), does a fine job of showing how you would use these tools outside the context of `DataInterface` and `NWBConverter` classes. From what I can tell now that we have enhanced that first section the only thing this last section is adding is the use of `make_or_load_nwbfile`. Since we are providing an in-memory NWB File in that section, it must be writing a new file, which is the same action that is being taken in the first section, and I think it would be confusing to show two different ways of doing the exact same thing.
> some edits to the backend configuration tutorial

- src/neuroconv/tools/nwb_helpers/_metadata_and_file_helpers.py
Discussion from issue https://github.com/catalystneuro/neuroconv/issues/910. @CodyCBakerPhD, this is what I had in mind.
> add logic to erase file if writing fails

- .github/workflows/dev-testing.yml
- .github/workflows/formatwise-installation-testing.yml
- .github/workflows/live-service-testing.yml
- .github/workflows/testing.yml
- .github/workflows/update-s3-testing-data.yml
- requirements-testing.txt
From the discussion on https://github.com/catalystneuro/neuroconv/pull/904 were some dependencies were installed implictly on the CI through testing libraries:
pytest-xdist and wheel.
I am moving the first to the testing-requirements file and leaving wheel out to see exactly where we neeed it. Either at the level of scanimage requirements or as a general testing dependency.
> Move testing dependencies on the CI to testing requirements.

- src/neuroconv/datainterfaces/ecephys/baserecordingextractorinterface.py
- src/neuroconv/datainterfaces/ecephys/intan/intandatainterface.py
I used the wrong semantic version because I did not expect another mini release of spikeinterface before the new one.
This is causing some problems to @luiztauffer.
> Fix check in intan datainterface for spikeinterface version

- CHANGELOG.md
- src/neuroconv/datainterfaces/ecephys/intan/intandatainterface.py
Also included in #933 but probably easier to make this quick improvement here.
This  propagates the annotations of intan that were made available on https://github.com/NeuralEnsemble/python-neo/pull/1477
> Propagate annotations to `IntanRecordingInterface`

- src/neuroconv/datainterfaces/ecephys/intan/intandatainterface.py
Spikeinterface has started using a pre-release system which broke some of the logic here. In short:
```python
spikeinterface_version
<Version('0.101.0rc0')>
spikeinterface_version <= Version("0.100")
False
Version("0.100") <= Version("0.100.6")
True
spikeinterface_version >= Version("0.101.0")
False
```
So I had to switch the comparisons here to the negative and don't use the patch part of the semantic versioning to codify intent.
> Fix intan version for extra attributes

- CHANGELOG.md
- src/neuroconv/datainterfaces/behavior/video/video_utils.py
I am calculating timestamps of hundreds of files and it does not make sense to have this in standard output.
I am adding an option to supress it but keeping the current default.
> Add option to supress tqdm progress bar in `VideoContext`

- src/neuroconv/datainterfaces/ecephys/intan/intandatainterface.py
I have been working on Intan recently.
Currently, the `IntanRecordingInterface` is making the assumption that the ports of the controller are electrode groups but this is not the case. There are cases where those digital channels are divided into smaller groups and there are cases where a single probe is connected to two ports.
I am removing all of those assumptions in this PR.
Other properties like native_channel_order are actually in the recording annotations which I am propagating here.
> Remove wrong assumptions about electrode metadata in Intan

- CHANGELOG.md
- src/neuroconv/tools/neo/neo.py
This PR is for the icephys submodule and interfaces
This PR is independent of the others (not forming a chain until it's necessary to do so) so can be merged whenever ready
> [Backend Configuration VIIIe] Purge H5DataIO references - Icephys

- CHANGELOG.md
- src/neuroconv/datainterfaces/behavior/lightningpose/lightningposedatainterface.py
This PR is for the LightningPose interface
This PR is independent of the others (not forming a chain until it's necessary to do so) so can be merged whenever ready
> [Backend Configuration VIIId] Purge H5DataIO references - LightningPose

- src/neuroconv/nwbconverter.py
Following the unification in #42 and the precedent in the run conversion for data interfaces:
https://github.com/catalystneuro/neuroconv/blob/f87955aa61f16f8531da97eda3e3b2afc1e98a66/src/neuroconv/basedatainterface.py#L155-L160
> Deprecate `converter.run_conversion` without nwbfile_path 

- CHANGELOG.md
- setup.py
- src/neuroconv/datainterfaces/behavior/deeplabcut/_dlc_utils.py
- src/neuroconv/datainterfaces/behavior/deeplabcut/deeplabcutdatainterface.py
- src/neuroconv/datainterfaces/behavior/deeplabcut/requirements.txt
- tests/test_on_data/test_behavior_interfaces.py
@h-mayorquin and I talked about this, and it's come up before in the past...
The DLC team has historically taken far too long to even respond to issues, let alone push fixes or review PRs on [dlc2nwb](https://github.com/DeepLabCut/DLC2NWB/tree/main)
So we're just porting over the util functions here so we have full control over making minor bug fixes or improvements like the recent container name exposure (and no doubt others we'll find over time)
cc @vigji I'll absorb your fixes from https://github.com/DeepLabCut/DLC2NWB/pull/23 and for rebase your NeuroConv PR to this one (assuming I can)
> Port over DLC conversion utils

- .github/workflows/build_and_upload_docker_image_dev.yml
- .github/workflows/build_and_upload_docker_image_latest_release.yml
- .github/workflows/build_and_upload_docker_image_yaml_variable.yml
The dev date tags are needlessly flooding the GHCR; apparently it keeps around any images that have a unique tag (which would apply to all date tags) and only overrides based on that (such as static `dev` tag)
Also wondered why the builds weren't triggering for latest release, realized it was a naming issue in the GitHub Action
> Remove date tags & debug release trigger for docker images

- CHANGELOG.md
- src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglx_utils.py
- src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
- tests/test_on_data/test_format_converters/spikeglx_multi_probe_metadata.json
- tests/test_on_data/test_format_converters/spikeglx_single_probe_metadata.json
- tests/test_on_data/test_format_converters/test_spikeglx_converter.py
- tests/test_on_data/test_metadata/test_spikeglx_metadata.py
In place of https://github.com/catalystneuro/neuroconv/pull/977
- Add shank id when available
- Add contact ids which contain a reference to the shank when it exists
- Remove references to shank when the probe does not have shanks in the probeinterface sense.
> Improve spikeglx metadata

- src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglx_utils.py
Coming from #986.
As discussed there there are many more probe types that we don't have:
https://github.com/SpikeInterface/probeinterface/blob/3728499714f68cfadaf76ef51b19eb8cc813b011/src/probeinterface/io.py#L1081-L1108
This is a temporary patch so the interfaces does not stop in its tracks when this information is missing.
Eventually, we should fetch this from probeinterface.
> Get default description for neuropixels probes 

- src/neuroconv/tools/spikeinterface/spikeinterface.py
`add_recording` is not showing up in the API somehow. I am wondering if it is the lack of docstring...
anyway, a docstring is good to add anyway so adding it here.
> Add docstring to add_recording

- CHANGELOG.md
- src/neuroconv/datainterfaces/ecephys/baserecordingextractorinterface.py
As in the title.
Also, removed a deprecated option from the docstring.
> Add default call to metadata in `BaseRecordingInterface`  `add_to_nwb` method.

- docs/conversion_examples_gallery/recording/plexon2.rst
Plexon 2 is unreliable on its opening and it has been getting on the way of CI doc testing. Steps have already been taken to improve the situation but meanwhile I am disabling this doctest by removing the  code directive `>>>`
https://github.com/NeuralEnsemble/python-neo/pull/1541
> Temporary supress failing plexon

- pyproject.toml
The latest version of pip just released yesterday breaks editable installs for older versions of setuptools:
https://pip.pypa.io/en/stable/news/#deprecations-and-removals
I am just pushing the minimal up so this does not break the editable installs of someone.
I am also removing wheel as a depedency which is a legacy behavior:
https://setuptools.pypa.io/en/stable/userguide/quickstart.html#basic-use
> Update setuptools version on build

- src/neuroconv/tools/roiextractors/imagingextractordatachunkiterator.py
- src/neuroconv/tools/spikeinterface/spikeinterfacerecordingdatachunkiterator.py
This is a link to the pdf that is broken now and even if it comes back might be moved in the future. I think it is better to tell users that they should look for the info in the hdf5 documentation and give them keywords.
> Fix broken link to hdf5 documentation about IO optimization

- docs/developer_guide/testing_suite.rst
The schema tests were moved to minimal on this https://github.com/catalystneuro/neuroconv/pull/1049 and a link in the developer docs no longer exists.
The link tests did not detect that on the spot because until the change is merged the link still exists. An edge case, I don't know if it is worth it to automatize it. Probably not.
> Remove broken links from developer docs

- CHANGELOG.md
- src/neuroconv/datainterfaces/ecephys/spikegadgets/spikegadgetsdatainterface.py
- src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxnidqinterface.py
- src/neuroconv/datainterfaces/ophys/hdf5/hdf5datainterface.py
- src/neuroconv/utils/types.py
Follow up to add remaining validation calls for interfaces using arrays
> [Pydantic IVb] Pydantic validation on arrays

- src/neuroconv/datainterfaces/ecephys/baserecordingextractorinterface.py
- src/neuroconv/datainterfaces/ecephys/basesortingextractorinterface.py
This is something that @CodyCBakerPhD requested from me a while ago and I forgot to do.
That warning is meant for people who will use this in preprocessing (and I think it should be triggered in a different place) but this should suppress this uninformative warning in our use case.
> Eliminate warning about setting timestamps in the ecephys stream

- CHANGELOG.md
- src/neuroconv/tools/spikeinterface/spikeinterface.py
- tests/test_ecephys/test_tools_spikeinterface.py
Fixed this bug and added a test.
> Fix a bug in `add_sorting_to_nwbfile` where `unit_electrode_indices` was only propagated if `waveform_means` was passed

- CHANGELOG.md
- src/neuroconv/datainterfaces/ecephys/intan/intandatainterface.py
- src/neuroconv/tools/spikeinterface/spikeinterface.py
- tests/test_on_data/ecephys/test_raw_recordings.py
- tests/test_on_data/ecephys/test_recording_interfaces.py
Because the metadata in metadata["Ecephys"]["ElectrodeGroups"] contains a contains a reference to a device here:
https://github.com/catalystneuro/neuroconv/blob/675ec48966eab421d25c15cd2ce6041ae6e8b34c/src/neuroconv/datainterfaces/ecephys/baserecordingextractorinterface.py#L92-L95
When the code hits these lines another device is created:
https://github.com/catalystneuro/neuroconv/blob/675ec48966eab421d25c15cd2ce6041ae6e8b34c/src/neuroconv/tools/spikeinterface/spikeinterface.py#L175-L184
This resulted in me getting an nwbfile with two devices Intan and the generic one that the default metadata included.
This PR fixes this, I added a test and took the opportunity to move the Intan tests to the new format.
Plus, I made a small improvement to the metadata where the specific controller that …
> Fix bug in Intan interface where extra device is written

- CHANGELOG.md
- pyproject.toml
- setup.py
- src/neuroconv/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
- src/neuroconv/datainterfaces/ecephys/blackrock/header_tools.py
- src/neuroconv/tools/roiextractors/roiextractors.py
- src/neuroconv/tools/spikeinterface/spikeinterface.py
- src/neuroconv/tools/testing/mock_probes.py
- src/neuroconv/utils/json_schema.py
> Using ruff rule to enforce the existence of docstrings in public functions

- CHANGELOG.md
- src/neuroconv/tools/testing/mock_interfaces.py
- tests/test_ophys/test_ophys_interfaces.py
These changes are necessary so the `get_extractor` method works with ` MockImagingInterface`
https://github.com/catalystneuro/neuroconv/blob/9a886587aece41b3be0c5951b2d6ed54ece83304/src/neuroconv/baseextractorinterface.py#L21-L31
> Make `get_extractor` work with `MockImagingInterface`

- .github/workflows/assess-file-changes.yml
- .github/workflows/deploy-tests.yml
- CHANGELOG.md
- docs/conversion_examples_gallery/conftest.py
The full tests also run the doctests so the "doctest only" workflow should only run when the normal tests are not running.
> Github CI only run doctests when tests are not run

- CHANGELOG.md
- src/neuroconv/datainterfaces/behavior/video/videodatainterface.py
- src/neuroconv/tools/testing/data_interface_mixins.py
- tests/test_behavior/test_video_interface.py
- tests/test_on_data/ecephys/test_recording_interfaces.py
This enables zarr testing for running conversions with backend specified as a string (still missing the building a backend configuration part)
It also makes some metadata checks proper tests on their own which has two advantages:
* They will fail on their own and be identified as such by pytest
* Can be parallelized with xdist.
> Enable zarr backend testing in data tests [1]

- .github/workflows/deploy-tests.yml
As in the title. 
@pauladkisson Here the idea is that the changelog check is only enforced when someone marks the PR as ready for review and from then onwards. This achieves the following which I find desirable:
* The PR should not be marked immediately as a failure as it is now when is on draft.
* PRs also change when they are in draft and the right point to write a changelog is when the PR is ready for review.
* It will save runners on the CI and currently, we are getting too little on them and waiting too long on our workflows.
> Only run changelog request when status is not draft

- CHANGELOG.md
- src/neuroconv/datainterfaces/ophys/basesegmentationextractorinterface.py
- src/neuroconv/tools/testing/mock_interfaces.py
- tests/test_ophys/test_ophys_interfaces.py
> Add `MockSegmentationInterface` 

- .github/workflows/test-external-links.yml
- CHANGELOG.md
As in the title. Related to #1082 and https://github.com/catalystneuro/neuroconv/pull/1078
> Avoid doing link check on draft

- .github/workflows/build_and_upload_docker_image_rclone_with_config.yml
- .github/workflows/weeklies.yml
- CHANGELOG.md
Continuation of #1081 for weekly workflows.
> reorganized weeklies into dedicated workflow like dailies

- .github/workflows/deploy-tests.yml
- CHANGELOG.md
As in the title. From the discussion on  https://github.com/catalystneuro/neuroconv/pull/1082#discussion_r1759632013
> Remove dev tests from the PR tests

- CHANGELOG.md
- src/neuroconv/tools/testing/data_interface_mixins.py
- tests/test_on_data/ecephys/test_recording_interfaces.py
- tests/test_ophys/test_ophys_interfaces.py
Final follow-up on #1083.
This checks that passing a backend_configurator object works with both zarr and hdf5.
> Enable zarr backend testing in data tests [3]

- .github/actions/load-data/action.yml
- .github/workflows/dev-testing.yml
- .github/workflows/doctests.yml
- .github/workflows/testing.yml
- CHANGELOG.md
While working on  #1013 I was having trouble getting the data right from the caches (see the diff in that PR). Centralizing the logic should make this kind of problem easier to deal with.
This is a partial move in the direction of #993.
> Use a github action to centralize gin data preparation

- docs/user_guide/docker_demo.rst
> Slimmer code blocks in Docker usage docs

- CHANGELOG.md
- src/neuroconv/datainterfaces/ecephys/edf/edfdatainterface.py
Related to #1106
This adds the user to the possibility of skipping non-neural channels on the EDF interface.
Some relevant comments:
* Can't add testing right now. The EDF by neo is blocked when reading the format. That means that it does not work well with the parallel machinery that we have in pytest. I have been meaning to fix this on the neo level or add a hack to our pytest machinery but other priorities come first (see https://github.com/NeuralEnsemble/python-neo/issues/1557).
* Up for debate on how to expose the available channels so the user can pick for them. Ideally, this should be a static or class method but then because of the blocking problem described in the previous point this will not work in a script (getting the channel names requires opening the file). Maybe this is …
> Add skip channels to EDF interface

- .pre-commit-config.yaml
- CHANGELOG.md
- src/neuroconv/tools/spikeinterface/spikeinterface.py
- tests/test_ecephys/test_tools_spikeinterface.py
Related to https://github.com/catalystneuro/neuroconv/issues/1106.
This produces error that look like this which should offer better diagnosis to users on which channels are the source of heterogeneity:
```
"Recording extractors with heterogeneous offsets are not supported.",
"Multiple offsets were found per channel IDs:",
"  Offset 0: Channel IDs ['a', 'b']",
"  Offset 1: Channel IDs ['c', 'd']",
"  Offset 2: Channel IDs ['e']",
```
> Add more friendly error when writing recording with multiple offsets

- src/neuroconv/datainterfaces/behavior/lightningpose/lightningposeconverter.py
- src/neuroconv/datainterfaces/ecephys/axona/axonadatainterface.py
- src/neuroconv/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
- src/neuroconv/datainterfaces/ecephys/openephys/openephysbinarydatainterface.py
- src/neuroconv/datainterfaces/ecephys/openephys/openephyssortingdatainterface.py
- src/neuroconv/datainterfaces/ecephys/spike2/spike2datainterface.py
- src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxconverter.py
- src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxnidqinterface.py
- src/neuroconv/datainterfaces/icephys/baseicephysinterface.py
- src/neuroconv/datainterfaces/ophys/brukertiff/brukertiffconverter.py
- src/neuroconv/datainterfaces/ophys/miniscope/miniscopeconverter.py
- src/neuroconv/tools/testing/mock_interfaces.py
- src/neuroconv/utils/__init__.py
- tests/test_minimal/test_utils/test_get_json_schema_from_method_signature.py
The method was deprecated but we are still using it in many places. This PR corrects that oversight.
> Change deprecated `get_schema_from_method_signature` to `get_json_schema_from_method_signature`

- CHANGELOG.md
- src/neuroconv/basedatainterface.py
- src/neuroconv/nwbconverter.py
- src/neuroconv/tools/testing/mock_interfaces.py
- src/neuroconv/utils/json_schema.py
- tests/test_minimal/test_interface_validation.py
Hi, @alessandratrapani .
I need to add a test but this is the reason you are seeing this error. As you might know we use json schema to do validation of the conversion options, metadata and interface arguments (source data).  The json schema validation requires arguments to be string and we use encoders to accomplish this. Check out the code. I still need to add a test for this but I wanted to share this with you as quick as possible.
A temporal solution in your code is to transform the datetime object to string (see the diff here for how) and then transform it back to datetime in `add_to_nwb`. But we can merge this quickly as well once I add a test.
> Support datetime in conversion options

- CHANGELOG.md
- src/neuroconv/tools/testing/data_interface_mixins.py
- tests/test_ecephys/test_ecephys_interfaces.py
- tests/test_ecephys/test_mock_recording_interface.py
We have specific tests for the mock recording interface that duplicates the tests on the mixing. This PR solves this by using the mixing tests for the mock (We already doing that in the ophys side). 
This PR also separates some changes that I did on https://github.com/catalystneuro/neuroconv/pull/1124 and should come before it.
> Use mixing tests for mocks

- CHANGELOG.md
- tests/test_minimal/test_tools/dandi_transfer_tools.py
We are getting failure on dandi tests on windows for well known reasons:
https://github.com/catalystneuro/neuroconv/pull/1086
The teardown mechanism of the unittest structure removes the directory which fails sometimes on windows because of permissions. This PR changes the testing from unittest to pytest so instead of using the ad-hoc teardown it uses pytest tmp_path methods which should be safer.
> Fix live-services tests (dandi) on windows

- CHANGELOG.md
- docs/conversion_examples_gallery/combinations/spikeglx_and_phy.rst
- docs/conversion_examples_gallery/recording/spikeglx.rst
- src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
- src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxnidqinterface.py
As this is an important change, we are giving it  a year instead of our typical six months. 
Should close #978
> Soft deprecate `file_path` for `SpikeGLXRecordingInterface` and `SpikeGLXNIDQInterface`

- CHANGELOG.md
- docs/conversion_examples_gallery/sorting/blackrock.rst
- docs/conversion_examples_gallery/sorting/neuralynx.rst
- src/neuroconv/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
- src/neuroconv/datainterfaces/ecephys/neuralynx/neuralynxdatainterface.py
- src/neuroconv/tools/spikeinterface/spikeinterface.py
- src/neuroconv/tools/testing/data_interface_mixins.py
- src/neuroconv/tools/testing/mock_interfaces.py
- tests/test_ecephys/test_ecephys_interfaces.py
- tests/test_minimal/test_tools/test_backend_and_dataset_configuration/test_helpers/test_configure_backend_defaults.py
- tests/test_minimal/test_tools/test_backend_and_dataset_configuration/test_helpers/test_configure_backend_equivalency.py
- tests/test_minimal/test_tools/test_backend_and_dataset_configuration/test_helpers/test_configure_backend_overrides.py
- tests/test_minimal/test_tools/test_backend_and_dataset_configuration/test_helpers/test_configure_backend_zero_length_axes.py
- tests/test_minimal/test_tools/test_backend_and_dataset_configuration/test_helpers/test_get_default_dataset_io_configurations_appended_files.py
- tests/test_on_data/ecephys/test_lfp.py
- tests/test_on_data/ecephys/test_raw_recordings.py
- tests/test_on_data/ecephys/test_sorting_interfaces.py
- tests/test_on_data/ecephys/test_spikeglx_converter.py
- tests/test_on_data/ecephys/test_spikeglx_metadata.py
I have been working on ecephys pipeline this week and these are some warnings that made it more difficult for me to find the errors. Besides, I am doing some other minor clean up.
* @pauladkisson, I am removing the stub tests that [we discussed before](https://github.com/catalystneuro/neuroconv/pull/1136#issuecomment-2475129398) as those are now tested with the mocking interface
* I am deprecating the `starting_time` of `add_electrical_series` as we have the time alignment methods now. We did the same in #1152
> Ecephys warnings removal and clean up 

- CHANGELOG.md
- src/neuroconv/datainterfaces/ecephys/baserecordingextractorinterface.py
- src/neuroconv/tools/testing/mock_interfaces.py
- tests/test_ecephys/test_ecephys_interfaces.py
Should fix #1163. 
Also related to https://github.com/catalystneuro/neuroconv/issues/932 as that should be more or less the last place where we did not priority set.
> Fix extra electrode groups ephys

- CHANGELOG.md
- docs/conversion_examples_gallery/fiberphotometry/tdt_fp.rst
- src/neuroconv/nwbconverter.py
- tests/test_on_data/ophys/test_miniscope_converter.py
Running local tests for the next release I noticed and changed three things:
1) The converter was missing the zarr option in the signature for typing. I added the typing and modified the docstring accordingly.
2) The miniscope tests were comparing session start time  with time zone included. This only works on the CI but fails locally if someone is not in the time zone of the CI server. I made the comparison on the naive datetime object only.
3) The TDT interface for fiber photometry is outputting files on the repo directory. I changed the conversion gallery so it uses the same machinery as all the other interfaces (where the output of the gallery is written to a temporary directory).
> Add missing typing to `NWBConverter` backend and backend options 

- pyproject.toml
- src/neuroconv/datainterfaces/behavior/lightningpose/lightningposedatainterface.py
- tests/test_on_data/behavior/test_behavior_interfaces.py
- tests/test_on_data/behavior/test_lightningpose_converter.py
Update ndx-pose to >= 0.2 for Lightning pose.
> Update ndx-pose for Lightning pose

- .gitignore
- CHANGELOG.md
- pyproject.toml
- tests/test_on_data/setup_paths.py
Currently, there are tests failing due to chunking errors with the latest release of hdmf:
https://github.com/catalystneuro/neuroconv/pull/1168
I am putting a ceiling on the version right now until we fix that. If I remember well this requires or would be helped by first fixing the PoseEstimation interfaces in other PRs.
> Set ceiling for HDMF to avoid failures with the latest release

- pyproject.toml
Should fix #1188
See related:
https://github.com/NeuralEnsemble/python-neo/pull/1635
https://github.com/SpikeInterface/spikeinterface/pull/3644
I don't think this needs a changelog.
> Update edf version

- CHANGELOG.md
- src/neuroconv/datainterfaces/ecephys/baserecordingextractorinterface.py
- src/neuroconv/datainterfaces/ophys/baseimagingextractorinterface.py
For ecephys interfaces, we call `get_metadata` when `metadata = None` in `add_to_nwbfile`. This is convenient because the default metadata is always added ensuring that the file is as complete as it can be with what can be extracted automatically.
This PR unifies the behavior between ophys and ecephys by adding this to ophys.
> Call get_metadata when no metadata is passed on ophys interfaces

- CHANGELOG.md
- src/neuroconv/datainterfaces/behavior/fictrac/fictracdatainterface.py
- tests/test_minimal/test_tools/test_backend_and_dataset_configuration/test_helpers/test_get_default_dataset_io_configurations.py
- tests/test_on_data/icephys/test_gin_icephys.py
Remove deprecated attributes and methods to enable pynwb 3.0 to run in our test suite.
> Add pynwb 3.0 support

- CHANGELOG.md
- src/neuroconv/datainterfaces/ophys/basesegmentationextractorinterface.py
Follow up on #1200. Explanation can be found there.
> Call `get_metadata` when no metadata is passed on segmentation interfaces 

- CHANGELOG.md
- src/neuroconv/tools/spikeinterface/spikeinterface.py
This is a weird behavior with numpy 2.0 in [this function](https://github.com/catalystneuro/neuroconv/blob/main/src/neuroconv/tools/spikeinterface/spikeinterface.py#L1815).
In the current implementation, applying `list` to `np.unique` [here](https://github.com/catalystneuro/neuroconv/blob/main/src/neuroconv/tools/spikeinterface/spikeinterface.py#L1820) results in:
```
print(group_names)
>>> [np.str_('ProbeA')]
```
This messes up the [pandas query](`https://github.com/catalystneuro/neuroconv/blob/main/src/neuroconv/tools/spikeinterface/spikeinterface.py#L1827`), which doesn't recognize the `np.` symbol.
This is a simple fix to make sure all elements of the `group_names` are parsed to python `str`
> Fix parsing of group names with numpy 2.0

- CHANGELOG.md
- src/neuroconv/tools/spikeinterface/spikeinterface.py
- src/neuroconv/tools/testing/data_interface_mixins.py
- tests/test_behavior/test_audio_interface.py
- tests/test_minimal/test_testing/test_mocks/test_mock_ttl.py
- tests/test_minimal/test_tools/test_backend_and_dataset_configuration/test_helpers/test_configure_backend_defaults.py
- tests/test_minimal/test_tools/test_signal_processing.py
- tests/test_on_data/test_temporal_alignment/test_temporal_alignment_methods.py
More support for numpy 2.0 in the testing suite.
* I need to change the representation in some warning functions because of this:
https://numpy.org/devdocs/release/2.0.0-notes.html#representation-of-numpy-scalars-changed
* And also:
> Use of keyword arguments x and y with functions assert_array_equal and assert_array_almost_equal has been deprecated. Pass the first two arguments as positional arguments instead.
https://numpy.org/devdocs/release/2.0.0-notes.html#deprecations
> Support numpy 2.0 in the testing suite.

- CHANGELOG.md
- tests/test_on_data/ophys/test_imaging_interfaces.py
This error has appeared on #1238 and #1117. I think it will break other tests on the CI and we should move fix it now. 
Part of the series of numpy 2.0 breaking changes I think.
> `np.NaN` to `np.nan`

- CHANGELOG.md
- pyproject.toml
Having many warnings on the CI makes navigating the CI log harder. For many tests, we artificially add a timezone because one isn't available, making the warning pointless in the CI context. I'd like to filter these warnings out of the CI. If there are cases where the timezone is critical, I believe we should have explicit test failures rather than warnings.
What do you think?
> Filter out warning for missing timezone in the CI

- CHANGELOG.md
- src/neuroconv/datainterfaces/ophys/scanimage/scanimageimaginginterfaces.py
- tests/test_on_data/ophys/test_imaging_interfaces.py
This came up working with the Kim Lab for the Cohen group conversion.
When using `ScanImageImagingInterface` with data with more than one channel or plane we throw an error indicating that we need to choose the channel. However, instead of just presenting the available channels to the user we tell them to use another method. 
This is unnecessary work for them, let's just give them the options on the spot. No point on making them do more work.
> Improve error on `ScanImageImagingInterface` with multiple channels

- .github/workflows/live-service-testing.yml
- CHANGELOG.md
They have been failing for a while. We believe this is a consequence of concurrent write access to the DANDI database. If this is correct, this should eliminate the problem.
That said, this solution may be too strong. A more precise alternative would be to have DANDI files that are OS- and Python-version-dependent, preventing overwriting of the same object. However, this approach is easier to implement, and the live service tests are not that long, so perhaps we should opt for the lower-effort solution.
> Add concurrency at the job level for live service tests

- CHANGELOG.md
- pyproject.toml
- src/neuroconv/datainterfaces/ecephys/cellexplorer/cellexplorerdatainterface.py
- src/neuroconv/datainterfaces/ecephys/sortedrecordinginterface.py
From https://github.com/catalystneuro/neuroconv/pull/1117
More NumPy representation fixes. Additionally, hdf5storage does not appear to have been updated to the latest version of NumPy. For `CellExplorer` this leads to failures.I am switching to pymatreader, which has the added advantage of providing a unified interface for both MATLAB formats (hdf5 and classic), simplifying the code slightly.
> More numpy 2.0 fixes

- .clinerules
- CHANGELOG.md
- docs/user_guide/adding_trials.rst
- docs/user_guide/backend_configuration.rst
- docs/user_guide/datainterfaces.rst
- src/neuroconv/basedatainterface.py
- src/neuroconv/nwbconverter.py
- src/neuroconv/tools/nwb_helpers/_metadata_and_file_helpers.py
In the documentation sometimes `save_path` is used and other times the correct `output_filepath`. I am fixing this and also changing the argument to `nwbfile_path` to unify this with other functions in the library.
> Fix use of `nwbfile_path`  in documentation of `configure_and_write_nwbfile`

- src/neuroconv/datainterfaces/behavior/video/externalvideointerface.py
- src/neuroconv/datainterfaces/behavior/video/internalvideointerface.py
- tests/test_behavior/test_external_video_interface.py
- tests/test_behavior/test_internal_video_interface.py
This escaped us in the recent merge. This does not need a changelog because is a fix for a bug that has not been released.
> Fix default metadata bug for ExternalVideoInterface

- src/neuroconv/datainterfaces/behavior/video/videodatainterface.py
- tests/test_behavior/test_video_interface.py
I think this is another regression caused by the recent changes. If metadata is not passed to the VideoInterface, it fails because the dictionary doesn't contain the expected behavior when reformatting the metadata.
No changelog for this either.
> Fix `VideoInterface` when metadata is not passed

- src/neuroconv/datainterfaces/behavior/video/externalvideointerface.py
- tests/test_behavior/test_external_video_interface.py
slightly different from what I described in #1279.
Basically, `set_aligned_segment_starting_times` assumes you want to save the full timestamps, and sets them automatically if they haven't been set already. Then, `set_aligned_starting_time` can be used if you want to use starting_time and rate.
> Update video timestamps

- CHANGELOG.md
- src/neuroconv/datainterfaces/behavior/video/externalvideointerface.py
- src/neuroconv/datainterfaces/behavior/video/internalvideointerface.py
- tests/test_behavior/test_external_video_interface.py
- tests/test_behavior/test_internal_video_interface.py
@pauladkisson as discussed during https://github.com/catalystneuro/neuroconv/pull/1251
This will unify video with ecehpys and ophys.
> Use `always_write_timestmaps` on the new video interfaces

- CHANGELOG.md
- docs/user_guide/adding_trials.rst
- docs/user_guide/backend_configuration.rst
- docs/user_guide/datainterfaces.rst
- src/neuroconv/tools/__init__.py
- src/neuroconv/tools/nwb_helpers/_metadata_and_file_helpers.py
- tests/imports.py
For the Cohen conversion, we're working with a lot of ad-hoc code where we add data directly to the NWBFile. At the end, we call configure_and_write_nwbfile to let users easily specify the backend.
I'd like to make this function importable from the top level of tools, since I often forget its exact location (currently, it's from neuroconv.tools.nwb_helpers import configure_and_write_nwbfile). Given how frequently we use it, I don't see any downside to exposing it at a higher level.
> Expose `configure_and_write_nwbfile` 

- CHANGELOG.md
- src/neuroconv/tools/spikeinterface/spikeinterface.py
- tests/test_ecephys/test_tools_spikeinterface.py
We have been discussing with the SpikeInterface team about improving unit handling [here](https://github.com/SpikeInterface/spikeinterface/pull/3844), and this is the first PR moving in that direction. This PR improves the following:
1) It checks whether the recording has the necessary information to scale to microvolts (gains and offsets). If not, it throws a warning and writes the data as it is. Note that, unlike before, it does not allow partially specified offsets and gains. This is in preparation for a future error that SpikeInterface will raise if units are not properly scalable to microvolts. I might make this an error once we make further changes in SpikeInterface as I don't want to break anything at the moment.
2) This should also fix #1266, which is currently not working and is …
> Improve ElectricalSeries units in recording interfaces

- CHANGELOG.md
- pyproject.toml
- src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxnidqinterface.py
- src/neuroconv/tools/spikeinterface/__init__.py
- src/neuroconv/tools/spikeinterface/spikeinterface.py
- tests/test_ecephys/test_tools_spikeinterface.py
As part of the ongoing effort to write all available data (i.e. not only neural) from a format in an easy way, this PR introduces the `add_time_series_to_nwbfile` function.
This function enables users to add non-neural recording data to NWB as a `TimeSeries`. It performs metadata validation and, when available, adds unit information, gains, and offsets.
This update also simplifies the process of integrating analog interfaces such as the `SpikeGLXNIDQInterface` interface, which I’ve refactored in this PR to demonstrate the new functionality.
Additional context comes from a request by @bendichter in this comment: https://github.com/catalystneuro/neuroconv/pull/1237#discussion_r1985650901
This complies with https://github.com/catalystneuro/neuroconv/issues/269 and #1280
> Add  `add_time_series_to_nwbfile` 

- .github/workflows/testing.yml
- CHANGELOG.md
- src/neuroconv/datainterfaces/ecephys/sortedrecordinginterface.py
- src/neuroconv/tools/spikeinterface/__init__.py
This should fix #1304. The specific error that trigger the user is now fixed on main but we should have a test for this (which I just added).
> Test that top level modules can be imported with minimal installation

- CHANGELOG.md
- src/neuroconv/datainterfaces/ophys/baseimagingextractorinterface.py
- src/neuroconv/tools/roiextractors/imagingextractordatachunkiterator.py
- tests/test_ophys/test_imagingextractordatachunkiterator.py
Two things:
1) Those parameters were previously not exposed, now they are.
2) Also, now that we are adjusting the semantics of frame-shape-sample I fixed the calculation of the max shape which is buggy at the moment because the previously `get_image_size` did return the size of the volume sometimes.
> Expose iterative write parameters on `BaseImagingExtractor`

- pyproject.toml
Until https://github.com/rly/ndx-pose/issues/40 gets fixed, sleap must be pinned to the older version.
> updated sleap version

- .github/workflows/dailies.yml
- .github/workflows/dev-dailies.yml
- CHANGELOG.md
I think this is the simplest option. The other option in #1342 works but is convoluted (you need to define inputs to the called workflows so they continue on fail but also return the true state as the output. I think this is simpler.
> Testing: separate dailies and dev-dailies

- CHANGELOG.md
- docs/api/tools.iterative_write.rst
- docs/api/tools.rst
- docs/developer_guide/building_documentation.rst
- docs/developer_guide/contributing.rst
- src/neuroconv/datainterfaces/behavior/video/internalvideointerface.py
- src/neuroconv/datainterfaces/behavior/video/video_utils.py
- src/neuroconv/tools/hdmf.py
- src/neuroconv/tools/iterative_write.py
- src/neuroconv/tools/nwb_helpers/_configuration_models/_base_dataset_io.py
- src/neuroconv/tools/roiextractors/imagingextractordatachunkiterator.py
- src/neuroconv/tools/spikeinterface/spikeinterfacerecordingdatachunkiterator.py
- tests/imports.py
- tests/test_behavior/conftest.py
- tests/test_behavior/test_internal_video_interface.py
- tests/test_behavior/test_video_utils.py
Should fix #1315
So we already had a `VideoDataChunkIterator` that we were not using. Most of this PR work was to align this iterator with the iterator for roiextractors so they match in the planar case.
> Add compression and chunking to `InternalVideoInterface`

- CHANGELOG.md
- src/neuroconv/utils/dict.py
- tests/test_minimal/test_utils/test_dict.py
Should fix #1350
After this PR the metadata (a deep dict) prints like this:
Whereas before this PR it printed like this:
(no nesting)
> Make DeepDict behave as normal dict when evaluated in notebooks

- CHANGELOG.md
- src/neuroconv/datainterfaces/image/imageinterface.py
- tests/test_image/test_image_interface.py
This comes from the Surmeier conversion where a stack of image is stored in this format.
This PR adds support for images with mode 'I;16' to the `ImageInterface` class. The 'I;16' mode is now mapped to `GrayscaleImage` in the NWB format.
'I;16' indicates 16-bit unsigned integer grayscale images. This is used in applications where higher bit depth is required for better dynamic range and precision compared to standard 8-bit grayscale images (mode 'L').
> Add support for `I;16` mode in `ImageInterface`

- .github/actions/load-data/action.yml
- .github/workflows/dev-testing.yml
- .github/workflows/doctests.yml
- .github/workflows/live-service-testing.yml
- .github/workflows/neuroconv_docker_testing.yml
- .github/workflows/testing.yml
- CHANGELOG.md
This is a discussion that started on 
https://github.com/catalystneuro/neuroconv/issues/1084 and https://github.com/catalystneuro/neuroconv/issues/993
Implements cross OS caching as described by the github actions docs:
https://github.com/actions/cache/blob/main/tips-and-workarounds.md#cross-os-cache
Which will reduce our cache usage by a factor three. This will be good to spend less on AWS downloads and also free the cache space we have so we can use it for dependency caching instead which in turn should make testing faster overall.
This is ready, To test this I erased all the caches before running this:
And now the actions is successful recovering the data with only one cache per modality instead one cache per modality per OS as we had before.
> Enable cross-os cache

- .github/workflows/copilot-setup-steps.yml
- .github/workflows/dev-testing.yml
- .github/workflows/formatwise-installation-testing.yml
- .github/workflows/live-service-testing.yml
- .github/workflows/test-external-links.yml
- .github/workflows/testing.yml
- .readthedocs.yaml
- CHANGELOG.md
- docs/developer_guide/building_documentation.rst
- docs/developer_guide/testing_suite.rst
- pyproject.toml
This should fix [issue #1366](https://github.com/catalystneuro/neuroconv/issues/1366).
I’ve been encountering dependency issues when trying to install neuroconv and solve the full installation. The problem is that the documentation dependencies are pinned to very specific versions (as they probably should be for reproducibility of the documentation style), but since they’re defined as extras, the package manager tries to resolve them and fails.
Fortunately, PEP 735 offers a clear solution by excluding these from the extras as dependency groups.
More concretely, this change reorganizes the testing, documentation, and development dependencies from [project.optional-dependencies] format into the new standardized [dependency-groups] section. Specifically, the test, docs, and dev (including …
> Use PEP 735 dependency groups

- CHANGELOG.md
- src/neuroconv/datainterfaces/ecephys/baserecordingextractorinterface.py
- src/neuroconv/tools/testing/data_interface_mixins.py
- tests/test_modalities/test_ecephys/test_ecephys_interfaces.py
This will close #1444.
In, https://github.com/catalystneuro/neuroconv/pull/1464, support to pobe groups was added but I realized that we don't really have good documentation or tests of this feature. 
This takes care of both.
> Add documentation and tests for set probe in recording interfaces

- CHANGELOG.md
- docs/_static/css/custom.css
- docs/_static/switcher.json
- docs/conf.py
Current we are using the RTD widget for switching between stable and latest versions of the documentation. This is a generic widget that RTD provides. 
On the other hand, we are using the PyData theme for our docs. This PR adds the [PyData native version switcher](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/version-dropdown.html) to the docs:
This change aligns our package with other documentation packages from the scientific Python ecosystem such as NumPy, SciPy and Scikit-learn in the placement of the version switcher (see https://numpy.org/doc/stable/ in the top upper corner). 
Once, and if, this is approved released we will remove the RTD native switcher as the latter needs to be deactivated on the RTD configuration (not in code).
Another benefit of this is that in …
> Use PyData theme  version switcher in the documentation

- docs/_static/css/neuroconv_assistant.css
- docs/_static/js/neuroconv_assistant.js
- docs/conf.py
- docs/index.rst
This is an alternative to https://github.com/catalystneuro/neuroconv/pull/1474 to add a chatbot.
This implementation displays the chatbot in an external window, which avoids the issues of content persistence when navigating through the Sphinx documentation.
You can check it out here:
https://neuroconv--1476.org.readthedocs.build/en/1476/
If we were to solve persistence within an anchored UI element and the current iframe setup, we would need to rely on JavaScript storage methods. Options here would include a URL-as-state mechanism or storage solutions such as localStorage or IndexedDB, both of which would introduce additional complexity and require changes in the nwb-assistant repository.
Using an external window instead has some potential advantages:
* Simplifies the implementation by …
> Add chatbot to docs (external window)

- docs/conf.py
Currently for build PRs the task switcher displays choose version by default. This changes this to the current format:
This has #1483 as a base.
> Fix version switcher in pr

- .github/workflows/auto-publish.yml
- CHANGELOG.md
Should fix #1491
I also added two other things:
1. The release should only run for tags that start with "v" allowing the use of tags for other purposes if necessary.
2. A rule-set (changed in settings) that restricts who can create tags as tagging triggers releases.
> Use attestation in auto-publish

- CHANGELOG.md
- src/neuroconv/tools/spikeinterface/spikeinterface.py
- tests/test_modalities/test_ecephys/test_tools_spikeinterface.py
Fixes #1499 
- Clarifies requirements of `sorting_analyzer.recording` or `recording` argument in the `write/add_sorting_analyzer_to_nwbfile`
- Added a test to mimic bad channel removal, i.e., the `SortingAnalyzer` has fewer channels than the externally provided raw recording
> Fix docs for add_sorting_analyzer and add test for sliced recording

- src/neuroconv/datainterfaces/ophys/miniscope/miniscopeimagingdatainterface.py
The previous miniscope extractor was too general. This PR temporary remaps this to the correct one before we amend the extractor, testing and documentation here.
> Miniscope temporary re-route

- CHANGELOG.md
- src/neuroconv/tools/roiextractors/roiextractors.py
- tests/test_modalities/test_ophys/test_tools_roiextractors.py
This is the first step to solve #1511. The idea here is to start from the top-down. First, define a immutable global reference for the ophys default metadata. Then, in other PRs, I will be clearing each of the writing branches of intermediate metadata mutations and only calling the defaults at the end.
> Simplify roiextractors metadata flow I 

- CHANGELOG.md
- tests/test_modalities/test_ophys/test_tools_roiextractors.py
While working on https://github.com/catalystneuro/roiextractors/pull/505 I noticed that there are some segmentation extractor tests that are failing because they are accessing private attributes of the segmentation extractor.
I am changing this here so only the public API is used.
In addition, I noticed a bug on roiextractors while fixing this:
https://github.com/catalystneuro/roiextractors/pull/508
So some tests will need to be temporarily commented out.
> Fix segmentation pipeline tests to only use public API of roiextractors
