catalystneuro/neuroconv

docs/conf.py

Trying to fix #46. This should close #46

Restore API documentation. 

---

docs/conf.py
requirements-rtd.txt

While working on #45 I noticed that are behind in most of the dependencies. Testing if this can be updated.

Update documentation dependencies

---

CHANGELOG.md
src/neuroconv/tools/roiextractors/roiextractors.py

This a small administrative PR that covers two points:
1. Two PRs (adding Neuralynx sorting data and enabling source code viewing) did not contain the corresponding modifications to the changelog. 
2. Moves the function `add_plane_segmentation` in the roiextractors module together with all the other `write_segmentation` functions (right now, it is on the write_imaging area) so as to keep the functions for the roiextractors module thematically organized together.

Forgotten updates to the CHANGELOG and small reorganization of roiextractors module

---

CHANGELOG.md
docs/developer_guide/style_guide.rst

There are some updates that are inspired by the comments in #28 but that I did not have the chance to apply. Also, adding this to the CHANGELOG as we did not added back at the time.

Small updates to the style guide

---

src/neuroconv/__init__.py

I think all I had to do (no pun intended) was specify the `__all__` attribute synchronized with the changes to `__dir__`
@bendichter @weiglszonja Can you two try to checkout this branch and before the following?
```python
import neuroconv
neuroconv.[type tab and see what it shows]
```
and
```python
from neuroconv import [type tab and see what it shows]
```
Also @h-mayorquin not sure how you prefer to run in-line auto-completion in VSCode, but if you can try and let me know.
I tested it on my system with IPython 7.34.0 and got the following
Then on latest jupyter version

Try auto parsing from __all__

---

src/neuroconv/tools/roiextractors/roiextractors.py

Create aux method for choosing iterator type (for #90)

---

tests/test_internals/test_roi_extractors_module.py

To be merged into https://github.com/catalystneuro/neuroconv/pull/90

Add more tests for `add_two_photon_series` ( for #90)

---

CHANGELOG.md
docs/conversion_example_gallery.rst
docs/conversion_examples_gallery/recording/abf.rst
src/neuroconv/datainterfaces/icephys/abf/abfdatainterface.py
tests/test_on_data/setup_paths.py

```
from neuroconv import NWBConverter, AbfInterface
class MyIcephysConverter(NWBConverter):
data_interface_classes = dict(AbfInterface=AbfInterface)
icephys_metadata = {
"cell_id": "20220512001",
"slice_id": "20220512001",
"targeted_layer": "L2-3(medial)",
"inferred_layer": "",
"recording_sessions": [
{
"abf_file_name": "2022_05_12_0000.abf",
"stimulus_type": "Long_Square_currentClamp_-50 to100_step10pA",
"icephys_experiment_type": "current_clamp"
}
]
}
source_data = dict(
AbfInterface=dict(
file_paths=["/media/luiz/storage/taufferconsulting/client_ben/project_icephys/22Q2_Ephys_DANDI/20220512001/2022_05_12_0000.abf"],
icephys_metadata=icephys_metadata
)
)
converter = MyIcephysConverter(source_data=source_data)
metadata = converter.get_metadata()
metadata['NWBFile']['identifier'] = …
```

abf interface improvements and tutorial

---

src/neuroconv/tools/roiextractors/roiextractors.py

Add missing annotation types in tools.ROIExtractors

---

CHANGELOG.md
docs/api/interfaces.icephys.rst
docs/api/interfaces.rst
src/neuroconv/datainterfaces/icephys/abf/abfdatainterface.py
src/neuroconv/datainterfaces/icephys/baseicephysinterface.py
src/neuroconv/tools/neo/neo.py

API documentation for Icephys: Abf interface

icephys api docs

---

CHANGELOG.md
docs/api/interfaces.ecephys.rst
docs/conversion_example_gallery.rst
docs/conversion_examples_gallery/recording/edf.rst
docs/conversion_examples_gallery/recording/tdt.rst
src/neuroconv/datainterfaces/ecephys/tdt/tdtdatainterface.py

Adds the TDT interface to the conversion gallery.
Should come after #70. It has this as its base.

Add TDT interface to conversion gallery

---

.github/workflows/formatwise_installation_testing.yml

Replaces to #115, could be merged without affecting primary workflows (would not show up on PRs, but can be triggered manually and will run on a schedule)

[Possible to merge][Testing]: Format-wise installation

---

CHANGELOG.md
src/neuroconv/datainterfaces/ophys/basesegmentationextractorinterface.py
src/neuroconv/tools/roiextractors/roiextractors.py
tests/test_ophys/test_tools_roiextractors.py

Add ROI centroid flag

---

docs/conversion_examples_gallery/behavior/deeplabcut.rst
docs/conversion_examples_gallery/imaging/hdf5imaging.rst
docs/conversion_examples_gallery/imaging/scanbox.rst
docs/conversion_examples_gallery/imaging/scanimage.rst
docs/conversion_examples_gallery/imaging/tiff.rst
docs/conversion_examples_gallery/recording/abf.rst
docs/conversion_examples_gallery/recording/axona.rst
docs/conversion_examples_gallery/recording/blackrock.rst
docs/conversion_examples_gallery/recording/edf.rst
docs/conversion_examples_gallery/recording/intan.rst
docs/conversion_examples_gallery/recording/neuralynx.rst
docs/conversion_examples_gallery/recording/neuroscope.rst
docs/conversion_examples_gallery/recording/openephys.rst
docs/conversion_examples_gallery/recording/spikegadgets.rst
docs/conversion_examples_gallery/recording/spikeglx.rst
docs/conversion_examples_gallery/segmentation/caiman.rst
docs/conversion_examples_gallery/segmentation/cnmfe.rst
docs/conversion_examples_gallery/segmentation/extract.rst
docs/conversion_examples_gallery/segmentation/suit2p.rst
docs/conversion_examples_gallery/sorting/cellexplorer.rst

What do y'all think of adding this to each of the conversion gallery entries?

add installation instructions for conversion gallery

---

src/neuroconv/tools/__init__.py
tests/test_minimal/test_import_structure.py

Remove tools alias

---

src/neuroconv/datainterfaces/ecephys/requirements.txt
src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
tests/test_on_data/test_metadata/test_spikeglx_metadata.py

This PR objective is to synch with the latest release and catch any bugs on the CI if they appear

Bump spikeinterface and neo versions

---

CHANGELOG.md
docs/conversion_example_gallery.rst
docs/conversion_examples_gallery/sorting/blackrock.rst
docs/conversion_examples_gallery/sorting/phy.rst
src/neuroconv/datainterfaces/behavior/deeplabcut/deeplabcutdatainterface.py
src/neuroconv/datainterfaces/ecephys/blackrock/blackrockdatainterface.py

#59 is too old and is easier to just re-start again from main.  This should close #57.

Port blackrock sorting interface to spikeinterface and conversion examples in gallery (II)

---

docs/conversion_examples_gallery/imaging/hdf5imaging.rst
docs/conversion_examples_gallery/imaging/scanbox.rst
docs/conversion_examples_gallery/imaging/tiff.rst
docs/conversion_examples_gallery/segmentation/caiman.rst
docs/conversion_examples_gallery/segmentation/cnmfe.rst
docs/conversion_examples_gallery/segmentation/extract.rst
docs/conversion_examples_gallery/segmentation/suite2p.rst

These lines were effectively deleting metadata that is populated by get_metadata.

remove metadata.update(NWBFile=dict()) from conversion gallery

---

docs/api/interfaces.ecephys.rst
docs/conversion_example_gallery.rst
docs/conversion_examples_gallery/recording/tdt.rst

Adding a conversion gallery example for #135. This has it as its base.

Add TDT data interface (II) - conversion gallery example-

---

src/neuroconv/datainterfaces/behavior/movie/moviedatainterface.py
src/neuroconv/utils/checks.py
tests/test_behavior/test_movie_interface.py

Increase precision of inferred regularity rates

---

CHANGELOG.md
src/neuroconv/datainterfaces/ecephys/baserecordingextractorinterface.py
src/neuroconv/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py

Small PR for the device of ecephys to best practices.

Change name of ecephys devices to follow best practices

---

CHANGELOG.md
docs/user_guide/schemas.rst
requirements-testing.txt
src/neuroconv/datainterfaces/ecephys/baselfpextractorinterface.py
src/neuroconv/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
src/neuroconv/datainterfaces/ecephys/intan/intandatainterface.py
src/neuroconv/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py
src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
src/neuroconv/tools/spikeinterface/spikeinterface.py
tests/test_ecephys/test_tools_spikeextractors.py
tests/test_ecephys/test_tools_spikeinterface.py
tests/test_on_data/test_gin_ecephys.py
tests/test_on_data/test_yaml_conversion_specification.py
tests/test_on_data/test_yaml_conversion_specification_cli.py

As described on the title. The issue of whether to capitalize LFP or Lfp in the camel case is still pending.

Change name of electrical series to follow best practices

---

docs/conversion_examples_gallery/behavior/deeplabcut.rst
docs/conversion_examples_gallery/behavior/sleap.rst
docs/conversion_examples_gallery/conversion_example_gallery.rst
docs/conversion_examples_gallery/imaging/hdf5imaging.rst
docs/conversion_examples_gallery/imaging/scanbox.rst
docs/conversion_examples_gallery/imaging/scanimage.rst
docs/conversion_examples_gallery/imaging/tiff.rst
docs/conversion_examples_gallery/recording/abf.rst
docs/conversion_examples_gallery/recording/axona.rst
docs/conversion_examples_gallery/recording/blackrock.rst
docs/conversion_examples_gallery/recording/edf.rst
docs/conversion_examples_gallery/recording/intan.rst
docs/conversion_examples_gallery/recording/neuralynx.rst
docs/conversion_examples_gallery/recording/neuroscope.rst
docs/conversion_examples_gallery/recording/openephys.rst
docs/conversion_examples_gallery/recording/spikegadgets.rst
docs/conversion_examples_gallery/recording/spikeglx.rst
docs/conversion_examples_gallery/recording/tdt.rst
docs/conversion_examples_gallery/segmentation/caiman.rst
docs/conversion_examples_gallery/segmentation/cnmfe.rst
docs/conversion_examples_gallery/segmentation/extract.rst
docs/conversion_examples_gallery/segmentation/suite2p.rst
docs/conversion_examples_gallery/sorting/blackrock.rst
docs/conversion_examples_gallery/sorting/cellexplorer.rst
docs/conversion_examples_gallery/sorting/kilosort.rst
docs/conversion_examples_gallery/sorting/neuralynx.rst
docs/conversion_examples_gallery/sorting/neuroscope.rst
docs/conversion_examples_gallery/sorting/phy.rst

* change title underlines
* listings are in alphabetical order
* add install step where missing
* don't convert to iso format- keep as datetime
* a few typos
What was the reasoning behind this change? Please explain the changes briefly.
```
Show here how to reproduce the new behavior (can be a bug fix or a new feature)
```

clean up tutorials

---

CHANGELOG.md
src/neuroconv/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
tests/test_on_data/test_gin_ecephys.py

Add multi stream support to `BlackrockRecordingExtractor` and automatic stream detection from filename. I also added some gin tests to cover this case.
This should fix #172.

Support multi stream support to `BlackrockRecordingExtractor`

---

.github/workflows/deploy-tests.yml
.github/workflows/dev-testing.yml
.github/workflows/doctests.yml
.github/workflows/formatwise-installation-testing.yml
.github/workflows/test-external-links.yml
.github/workflows/testing.yml
.github/workflows/update-caches.yml
CHANGELOG.md
src/neuroconv/basedatainterface.py
src/neuroconv/datainterfaces/ecephys/ced/ceddatainterface.py
src/neuroconv/datainterfaces/ecephys/ced/requirements.txt
src/neuroconv/tools/importing.py
tests/test_ecephys/test_ecephys_interfaces.py
tests/test_on_data/test_gin_ecephys.py

Changing the testing suite to see if works with pyhton 3.10

Support python 3.10

---

docs/index.rst

Removing this note as it may dissuade some users from trying to adopt the package

Remove alpha-dev note in docs

---

.github/ISSUE_TEMPLATE/format_request.yml
CHANGELOG.md

Add new form for new formats

---

CHANGELOG.md
docs/conversion_examples_gallery/conversion_example_gallery.rst
docs/conversion_examples_gallery/recording/biocam.rst
src/neuroconv/datainterfaces/__init__.py
src/neuroconv/datainterfaces/ecephys/biocam/biocamdatainterface.py
tests/test_on_data/test_gin_ecephys.py

fix #209
Adding a BiocamRecordingInterface.
No rich metadata/annotations. No session start time.
Example output file: [BiocamRecordingInterface_biocam.zip](https://github.com/catalystneuro/neuroconv/files/10078080/BiocamRecordingInterface_biocam.zip)
Test on GIN data added.

Add BiocamRecordingInterface

---

CHANGELOG.md
docs/conversion_examples_gallery/conversion_example_gallery.rst
docs/conversion_examples_gallery/recording/mcsraw.rst
src/neuroconv/datainterfaces/__init__.py
src/neuroconv/datainterfaces/ecephys/mcsraw/mcsrawdatainterface.py
tests/test_on_data/test_gin_ecephys.py

fix #214 
Adding a MCSRawRecordingInterface.
No rich metadata/annotations. No session start time.
Example output file: [MCSRawRecordingInterface_rawmcs.zip](https://github.com/catalystneuro/neuroconv/files/10099127/MCSRawRecordingInterface_rawmcs.zip)
Test on GIN data added.

Add MCSRawRecordingInterface

---

CHANGELOG.md
src/neuroconv/tools/spikeinterface/spikeinterface.py

rmv distutils

---

CHANGELOG.md
docs/api/basedatainterface.rst
docs/index.rst
docs/user_guide/datainterfaces.rst
docs/user_guide/user_guide.rst
docs/user_guide/yaml.rst
src/neuroconv/schemas/metadata_schema.json

* add dedicated docs page for yaml
* expand schema for NWBFile

dedicated docs for YAML metadata

---

CHANGELOG.md
src/neuroconv/tools/spikeinterface/spikeinterface.py
src/neuroconv/tools/spikeinterface/spikeinterfacerecordingdatachunkiterator.py

Adding DeprecationWarnings to tools as well.

Deprecate spikeextractors tools

---

CHANGELOG.md
docs/conversion_examples_gallery/sorting/plexon.rst
src/neuroconv/datainterfaces/__init__.py
src/neuroconv/datainterfaces/ecephys/plexon/plexondatainterface.py
tests/test_on_data/test_gin_ecephys/test_sorting.py
tests/test_on_data/test_metadata/test_plexon_metadata.py

Add interface for plexon spiking data, uses `spikeinterface.extractors.PlexonSortingExtractor`
`PlexonSortingInterface` is tested in `test_sorting.py`

Add `PlexonSortingInterface`

---

CHANGELOG.md
README.md
docs/developer_guide.rst
docs/developer_guide/building_documentation.rst

While improving other docs I saw this and figured I might as well

Move doc build instructions to docs

---

.codespellrc
.github/workflows/codespell.yml
CHANGELOG.md
docs/conversion_examples_gallery/recording/neuralynx.rst
docs/conversion_examples_gallery/recording/openephys.rst
docs/developer_guide/contributing.rst
docs/developer_guide/style_guide.rst
src/neuroconv/datainterfaces/ecephys/axona/axona_utils.py
src/neuroconv/datainterfaces/ecephys/blackrock/header_tools.py
src/neuroconv/datainterfaces/ecephys/neuroscope/neuroscope_utils.py
src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglx_utils.py
src/neuroconv/nwbconverter.py
src/neuroconv/tools/data_transfers.py
src/neuroconv/tools/roiextractors/roiextractors.py
src/neuroconv/tools/spikeinterface/spikeinterface.py
src/neuroconv/utils/globbing.py
tests/imports.py
tests/test_behavior/test_video_interface.py
tests/test_ecephys/test_tools_spikeinterface.py
tests/test_on_data/test_gin_behavior.py
tests/test_on_data/test_gin_ecephys/test_lfp.py
tests/test_on_data/test_gin_ophys.py
tests/test_on_data/test_temporal_alignment/test_temporal_alignment_methods.py
tests/test_ophys/test_tools_roiextractors.py

I saw #325 and was proud of @CodyCBakerPhD to a degree that I decided to contribute while being on the quest already trying out my fresh
<details>
<summary>helper script</summary> 
```bash
#!/bin/bash
set -eu
branch=$(git rev-parse --abbrev-ref HEAD)
if ! git remote | grep gh-yarikoptic; then
GH_TOKEN=$(git config hub.oauthtoken) gh repo fork --remote --remote-name gh-yarikoptic
fi
git checkout -b enh-codespell
mkdir -p .github/workflows
cat > .github/workflows/codespell.yml << EOF
---
name: Codespell
on:
push:
branches: [$branch]
pull_request:
branches: [$branch]
jobs:
codespell:
name: Check for spelling errors
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v3
- name: Codespell
uses: codespell-project/actions-codespell@v1
EOF
git add .github/workflows/codespell.yml …
```

Enh codespell

---

src/neuroconv/tools/data_transfers.py
tests/test_minimal/test_tools/test_dandi_transfer_tools.py

Confused why there are problems with tests in https://github.com/catalystneuro/neuroconv/pull/349
No dandi releases since then, most recent scheduled tests on main ran fine

Test DANDI upload issue

---

tests/test_minimal/test_tools/test_dandi_transfer_tools.py

Service issues should be fixed now

Restore DANDI transfer test

---

CHANGELOG.md
src/neuroconv/utils/json_schema.py
tests/test_minimal/test_utils/test_json_schema_utils.py

fix #358
@weiglszonja can you please see if this fixes your problem?

get_schema_from_method_signature can now handle `Dict[str, str]``

---

CHANGELOG.md
src/neuroconv/basedatainterface.py
src/neuroconv/utils/json_schema.py

Opened as a follow-up on https://github.com/catalystneuro/neuroconv/pull/372

Auto-generate source schema upon __new__ `BaseDataInterface`

---

src/neuroconv/datainterfaces/ecephys/requirements.txt

I had some issues with the SortingExtractorInterface until I updated spikeinterface

Update ecephys requirements.txt

---

requirements-minimal.txt

CI failing lately; seeing if it's due to recent PyNWB changes

Trying to mix 3.11 tests on main

---

src/neuroconv/schemas/base_metadata_schema.json

Looks like this wasn't required on the metadata schema side

Make session start time required

---

src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxconverter.py

* Fixed `get_conversion_options_schema`
* removed .run_conversion

[SpikeGLXConverter]: fix conversion options, change to NWBConverter

---

CHANGELOG.md
src/neuroconv/datainterfaces/ecephys/baserecordingextractorinterface.py
src/neuroconv/tools/testing/data_interface_mixins.py
tests/test_on_data/test_recording_interfaces.py

@garrettmflynn My first attempts at getting this to work for your table in the GUIDE app

Add electrode property retrieval helper for GUIDE

---

src/neuroconv/schemas/base_metadata_schema.json

This ended up being the source of the issue with the GUIDE rendering of those fields @garrettmflynn

Fix text characters in schema

---

CHANGELOG.md
src/neuroconv/datainterfaces/ecephys/baselfpextractorinterface.py
tests/test_on_data/test_gin_ecephys/test_lfp.py

Change LFP naming convention for `es_key`

---

CHANGELOG.md
src/neuroconv/tools/nwb_helpers.py
src/neuroconv/utils/json_schema.py
tests/test_minimal/test_tools/test_nwb_helpers.py

remove deep_dict_update from make_nwbfile_from_metadata()

---

src/neuroconv/datainterfaces/ecephys/requirements.txt

fix #509 temporarily until neo/SI fixes and rereleases

Downpin SpikeInterface for tests

---

src/neuroconv/utils/json_schema.py

@garrettmflynn found a minor issue with the source schema setter for certain interfaces - namely if the signature specifies a Union (which includes Optional) of one of our path types, then it's JSON 'format' won't get updated correctly
Has no effect on NeuroConv itself, but the GUIDE uses this JSON field to determine parameters of  drag-and-drop form component

[Bug] Fix path format in source schema with Optional

---

src/neuroconv/datainterfaces/ecephys/requirements.txt

New spikeinterface release that might help us solve the issues that arose in:
https://github.com/catalystneuro/neuroconv/issues/509
Let's test.

Bump spikeinterface version

---

CHANGELOG.md
setup.py
src/neuroconv/tools/roiextractors/roiextractors.py
tests/test_ophys/test_tools_roiextractors.py

Commenting out is not a solution, we'll need to do that part more efficiently.
https://github.com/catalystneuro/neuroconv/issues/528

Need to change filtering all zero data from `add_fluorescence_traces`

---

tests/test_behavior/test_video_utils.py
tests/test_minimal/test_tools_hdmf.py

Latest HDMF release raised default chunk sizes which broke a couple of tests on `main`
Simple fixes, all

Fix tests on main

---

.github/workflows/doctests.yml
CHANGELOG.md
docs/api/interfaces.behavior.rst
docs/conversion_examples_gallery/behavior/fictrac.rst
docs/conversion_examples_gallery/conversion_example_gallery.rst

Add fictrac to the conversion gallery and API documentation

---

README.md

As in the title. Very simple fix.

Master to main in installation instructions in the readme.

---

CHANGELOG.md
src/neuroconv/datainterfaces/ecephys/openephys/openephyslegacydatainterface.py
tests/test_on_data/test_gin_ecephys/test_openephyslegacy.py

Fix date parsing in `OpenEphysLegacyRecordingInterface`

---

tests/test_ecephys/test_tools_spikeinterface.py

Reported broken in slack.
Related to this:
https://github.com/SpikeInterface/spikeinterface/issues/2052

Fix dev tests  (waveform quality metrics bug)

---

docs/catalogue/catalogue.rst

CI on other PR indicated broken link; looks like princeton updated their links

Update broken link

---

CHANGELOG.md
src/neuroconv/tools/roiextractors/roiextractors.py

The time is here. Deprecations yei!
Removed some long-commented code as well.

Deprecate `use_times` in `add_photon_series`

---

src/neuroconv/datainterfaces/behavior/fictrac/fictracdatainterface.py
tests/test_on_data/test_behavior_interfaces.py

Builds on #606. Adds the setters and getters to `FicTracDataInterface`.

Add time setters and getters to `FicTracDataInterface`

---

CHANGELOG.md
src/neuroconv/datainterfaces/ecephys/neuroscope/neuroscope_utils.py
src/neuroconv/tools/testing/mock_interfaces.py
tests/test_ophys/test_ophys_interfaces.py

This will be useful for testing some current and future problems.

Add imaging mock interface

---

CHANGELOG.md
src/neuroconv/tools/data_transfers.py
tests/test_minimal/test_tools/dandi_transfer_tools.py

@garrettmflynn 
Looks like this actually will need one small PR on DANDI to fully expose a certain argument
But there might be a way to work around it for now

Expose DANDI upload job parameters

---

CHANGELOG.md
requirements-minimal.txt
src/neuroconv/tools/spikeinterface/spikeinterfacerecordingdatachunkiterator.py

An improvement that is only applicable to latest releases of HDMF (might need to bump lower version here)

Improve chunking pattern for ecephys recording

---

src/neuroconv/schemas/base_metadata_schema.json
src/neuroconv/schemas/metadata_schema.json

This PR updates the description for the `virus` field to what is expected from the NWB Schema.

Update virus description

---

tests/imports.py

Small improvement to import test

---

docs/developer_guide/testing_suite.rst

[Documentation] Fix installation typo

---

docs/developer_guide/testing_suite.rst

Add note to testing suite instructions

---

src/neuroconv/tools/testing/data_interface_mixins.py

Same logic as with recording:
https://github.com/catalystneuro/neuroconv/blob/6fa51c39084a8f198e0489c36d06fa8cf3d881ee/src/neuroconv/tools/testing/data_interface_mixins.py#L292-L299

Fix sorting tests

---

CHANGELOG.md
src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxconverter.py
src/neuroconv/tools/spikeinterface/spikeinterface.py
tests/test_on_data/test_format_converters/test_spikeglx_converter.py

Fix `SpikeGLXConverterPipe` writing to electrodes table

---

tests/test_on_data/test_format_converters/test_spikeglx_converter.py

Less confident as this one so opening it as a chained PR to the first one in #688. 
Tell me what you think @alejoe91 and @CodyCBakerPhD .

 #688 roundtrip test with Spikeinterface

---

CHANGELOG.md
src/neuroconv/datainterfaces/ecephys/openephys/openephysbinarydatainterface.py
src/neuroconv/datainterfaces/ecephys/openephys/openephysdatainterface.py
src/neuroconv/datainterfaces/ecephys/openephys/openephyslegacydatainterface.py
tests/test_on_data/test_recording_interfaces.py

Exposed block_index to OpenEphys interfaces

---

.github/workflows/testing.yml
tests/test_minimal/test_metadata_schema.py

Daily tests just started failing due to new release of jsonschema

Fix for latest release of jsonschema

---

src/neuroconv/utils/json_schema.py

* add _is_member convenience function
* pull out arg name and type
* build the schema value on its own

simplify get_schema_from_hdmf_class

---

docs/api.rst
docs/conf.py
docs/index.rst
requirements-rtd.txt

change docs to pydata theme

---

docs/conversion_examples_gallery/behavior/fictrac.rst

@bendichter and I noticed that the FicTrac docs weren't quite correct and could be improved.

Improve fictrac docs

---

docs/conversion_examples_gallery/recording/plexon.rst

@bendichter This part should no longer be necessary then, I assume

Update plexon example to only update timezone

---

requirements-minimal.txt

Update HDMF pin

---

CHANGELOG.md
requirements-testing.txt
src/neuroconv/datainterfaces/ophys/scanimage/scanimageimaginginterface.py

Reference ROIExtractors for ScanImage metadata

---

CHANGELOG.md
src/neuroconv/tools/path_expansion.py
tests/test_minimal/test_tools/test_expand_paths.py

address https://github.com/NeurodataWithoutBorders/nwb-guide/issues/528

[Feature] Create template fstring path from real path

---

.github/workflows/dev-testing.yml

As in the title. It will be useful to fix stuff in advance.

Add HDFM zarr to dev testing

---

src/neuroconv/schemas/base_metadata_schema.json

Detected while fixing https://github.com/NeurodataWithoutBorders/nwb-guide/pull/639

Include taxonomy on JSON schema regex pattern for species

---

src/neuroconv/tools/data_transfers/_dandi.py

Requested by https://github.com/NeurodataWithoutBorders/nwb-guide/issues/658#issuecomment-1989243735
Give this a try and let me know

Return organized files from DANDI upload

---

.github/ISSUE_TEMPLATE/bug_report.yml

fix issue template Python versions

---

.github/workflows/testing.yml

Dailies are triggered in a separate workflow: https://github.com/catalystneuro/neuroconv/blob/main/.github/workflows/dailies.yml#L22

Undo CRON for testing.yml

---

docs/index.rst

From #730. This is a request by @pauladkisson .
I wanted to create another PR as I feel these two things are separated concerns that should thrive or fall on their own.

Remove redundant doctree

---

CHANGELOG.md
src/neuroconv/tools/spikeinterface/spikeinterface.py
tests/test_ecephys/test_tools_spikeinterface.py

@alejoe91 any idea how to add tests for this?

Fix write_waveforms nwbfile call

---

README.md

fix daily test readme badge

---

CHANGELOG.md
src/neuroconv/datainterfaces/behavior/video/videodatainterface.py
src/neuroconv/tools/neo/neo.py

This was discovered by @CodyCBakerPhD in #801
I am pushing her to get this fix to the main branch as quick as possible.

Avoid modifying metadata in-place in the `VideoInterface` and `AbfInterface`

---

src/neuroconv/tools/nwb_helpers/_configure_backend.py

From https://github.com/catalystneuro/neuroconv/pull/801/files#r1563407091

[Backend Configuration IVb] Swap internal variable name for consistency

---

.github/workflows/dev-testing.yml
CHANGELOG.md
docs/developer_guide/schemas.rst
src/neuroconv/datainterfaces/ecephys/baserecordingextractorinterface.py
src/neuroconv/datainterfaces/ecephys/basesortingextractorinterface.py
src/neuroconv/datainterfaces/ophys/baseimagingextractorinterface.py
src/neuroconv/datainterfaces/ophys/miniscope/miniscopeimagingdatainterface.py
src/neuroconv/utils/json_schema.py

Update all definition references

---

CHANGELOG.md
src/neuroconv/basedatainterface.py
src/neuroconv/tools/nwb_helpers/_configure_backend.py

Some docstring inconsistencies spotted by @bendichter

Fix backend docstrings

---

CHANGELOG.md
src/neuroconv/datainterfaces/ecephys/basesortingextractorinterface.py

@garrettmflynn Give this a try

Debug `None` segment `_t_start` in SortingInterface alignment

---

.github/workflows/doctests.yml
docs/catalogue/catalogue.rst
tests/test_on_data/test_imaging_interfaces.py

@h-mayorquin Looks like this one legit disappeared entirely

Remove broken link

---

.github/workflows/testing.yml
CHANGELOG.md
docs/conversion_examples_gallery/recording/edf.rst
tests/test_on_data/test_imaging_interfaces.py

Debug scanimage tests

---

requirements-minimal.txt
tests/test_on_data/test_format_converters/test_lightningpose_converter.py
tests/test_on_data/test_format_converters/test_miniscope_converter.py
tests/test_on_data/test_format_converters/test_spikeglx_converter.py

These started failing on dev a few days ago, just now getting around to fixing them

Fix latest pynwb tests

---

docs/user_guide/backend_configuration.rst

@CodyCBakerPhD something like this

Backend config docs3

---

src/neuroconv/tools/nwb_helpers/_configuration_models/_base_backend.py
src/neuroconv/tools/nwb_helpers/_configuration_models/_hdf5_backend.py
src/neuroconv/tools/nwb_helpers/_configuration_models/_zarr_backend.py
tests/test_minimal/test_tools/test_backend_and_dataset_configuration/test_helpers/test_get_default_backend_configuration.py
tests/test_minimal/test_tools/test_backend_and_dataset_configuration/test_models/test_hdf5_backend_configuration_model.py
tests/test_minimal/test_tools/test_backend_and_dataset_configuration/test_models/test_zarr_backend_configuration_model.py

From https://github.com/catalystneuro/neuroconv/pull/802#discussion_r1590476370

Style suggestions from other PR

---

docs/developer_guide/testing_suite.rst

Some feedback on confusion from @mavaylon1 (who is trying to set these up on HDMF for early warning of breakages)

Adjust data install instructions

---

CHANGELOG.md
src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxconverter.py

Of an unneeded field in the Converter case (specific to the NIDQ portion)

Attempt to fix GUIDE electrode table rendering

---

docs/developer_guide/build_data_interface.rst

Updated documentation to reflect the change from `run_conversion` to `add_to_nwbfile`

Updated DataInterface Documentation

---

CHANGELOG.md
src/neuroconv/tools/spikeinterface/spikeinterface.py
tests/test_ecephys/test_tools_spikeinterface.py

Add support for double ragged arrays on `add_electrodes`

---

tests/test_on_data/test_format_converters/test_lightningpose_converter.py
tests/test_on_data/test_format_converters/test_miniscope_converter.py
tests/test_on_data/test_format_converters/test_spikeglx_converter.py

Since the change is soon to be reverted

Restore previous timezone tests

---

CHANGELOG.md
src/neuroconv/datainterfaces/ecephys/baserecordingextractorinterface.py

@h-mayorquin Found this problem via the GUIDE
How would you like it to be tested?

[Bug] Fix stub times in recording interface

---

CHANGELOG.md
src/neuroconv/tools/nwb_helpers/_metadata_and_file_helpers.py

@garrettmflynn Minor typo, prevented GUIDE watermark from applying

Debug conditional addition of watermark

---

tests/test_ecephys/test_tools_spikeinterface.py

fix dev tests spikeinterface

---

CHANGELOG.md
src/neuroconv/tools/nwb_helpers/_metadata_and_file_helpers.py
tests/test_behavior/test_audio_interface.py
tests/test_minimal/test_tools/test_context_tools.py

Fix overwrite on corrupt file

---

src/neuroconv/datainterfaces/ecephys/spike2/spike2datainterface.py

From https://github.com/NeurodataWithoutBorders/nwb-guide/issues/882
NeuroConv has only supported `.smrx` to this point; it would be a separate feature to investigate support for the `.smr`

Update Spike2 suffixes

---

CHANGELOG.md
src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxconverter.py
src/neuroconv/nwbconverter.py
tests/test_on_data/test_format_converters/test_spikeglx_converter.py

fix #919 
cc @rly If you dev install with this does it help?

Fix SpikeGLXConverter conversion option schema

---

CHANGELOG.md
src/neuroconv/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py
tests/test_on_data/test_sorting_interfaces.py

Should fix https://github.com/NeurodataWithoutBorders/nwb-guide/issues/881
I'll add a test case tomorrow

Fix conditional existence of xml path

---

src/neuroconv/datainterfaces/behavior/video/videodatainterface.py

Docstring improvements to #914.
Is this how this should work?
The thing that I am confused about is, when will add multiple videos in one interface vs separate videos.

Docstring  improvements

---

CHANGELOG.md
src/neuroconv/datainterfaces/behavior/video/videodatainterface.py
tests/test_behavior/test_video_interface.py

multi videos

---

src/neuroconv/datainterfaces/ecephys/spike2/spike2datainterface.py

Change Spike2 associated_suffixes from str to list

---

CHANGELOG.md
src/neuroconv/datainterfaces/behavior/audio/audiointerface.py
src/neuroconv/tools/audio/audio.py

This PR is for the audio tools and interfaces

[Backend Configuration VIIIa] Purge H5DataIO references - Audio

---

CHANGELOG.md
src/neuroconv/datainterfaces/behavior/fictrac/fictracdatainterface.py

This PR is for the FicTrac  interface
This PR is independent of the others (not forming a chain until it's necessary to do so) so can be merged whenever ready

[Backend Configuration VIIIc] Purge H5DataIO references - FicTrac

---

CHANGELOG.md
src/neuroconv/datainterfaces/ophys/basesegmentationextractorinterface.py
src/neuroconv/tools/roiextractors/roiextractors.py
tests/test_ophys/test_tools_roiextractors.py

This PR is for the ophys tools and interfaces
This PR is independent of #939 (not forming a chain until it's necessary to do so) so can be merged whenever ready

[Backend Configuration VIIIb] Purge H5DataIO references - Ophys

---

CHANGELOG.md
src/neuroconv/datainterfaces/ophys/tdt_fp/informal_test.py
src/neuroconv/datainterfaces/ophys/tdt_fp/tdtfiberphotometrydatainterface.py

TDT fiber photmetry changes

---

src/neuroconv/datainterfaces/behavior/medpc/medpcdatainterface.py

@pauladkisson Wow, I completely missed this on review of your PR
GUIDE needs these to be a tuple, even of a single element
Since you're taking over DevOps, it might be a good idea to setup dev testing of NWB GUIDE on NeuroConv to ensure this kind of thing doesn't happen silently and slowly creep up over there

Fix suffixes for GUIDE

---

src/neuroconv/datainterfaces/behavior/medpc/medpcdatainterface.py
tests/test_minimal/test_tools/test_importing.py

More Detailed Testing of GUIDE attrs

---

src/neuroconv/datainterfaces/icephys/baseicephysinterface.py

Imports should be done at __init__.
This is better for performance.

Delay import of DandiIcephysMetadata

---

CHANGELOG.md
src/neuroconv/datainterfaces/behavior/deeplabcut/_dlc_utils.py
src/neuroconv/datainterfaces/behavior/deeplabcut/deeplabcutdatainterface.py

Agreed follow up on https://github.com/catalystneuro/neuroconv/pull/967 
Check it out @vigji  
Note that a half an hour video took less than a minute in my computer. Your performance was way worse @vigji ?

Add timestamps optimization warning in dlc

---

src/neuroconv/datainterfaces/behavior/fictrac/fictracdatainterface.py

Granted it's only for a month and half more

Fix FicTrac warning

---

CHANGELOG.md
src/neuroconv/datainterfaces/behavior/video/videodatainterface.py
tests/test_behavior/test_video_utils.py

Deprecate H5DataIO from videointerface

---

docs/conf.py
src/neuroconv/tools/testing/data_interface_mixins.py

[Documentation] Remove private members from api

---

docs/user_guide/expand_path.rst
tests/test_minimal/test_tools/test_expand_paths.py

Granted they aren't associated with anything that uses Pydantic, but still - might as well update it now since we can

Remove more old typings

---

src/neuroconv/utils/__init__.py
src/neuroconv/utils/types.py

As per meeting today
@h-mayorquin after this you are probably good for a fresh release

[Pydantic IV] Restore soft deprecation of old types

---

src/neuroconv/datainterfaces/ecephys/plexon/plexondatainterface.py

Related to recent changes at the python-neo level some dev tests are failing here.

Fix Plexon2 in dev tests

---

CHANGELOG.md
src/neuroconv/tools/testing/__init__.py
src/neuroconv/tools/testing/mock_interfaces.py
tests/test_ecephys/test_ecephys_interfaces.py

As in the title. Needed for testing things like this:
https://github.com/catalystneuro/neuroconv/pull/1053#issuecomment-2332697924

Add  `MockSortingInterface`

---

.pre-commit-config.yaml
CHANGELOG.md
pyproject.toml

I was waiting on python-neo to make a release so we can make a minor release of neuroconv.
After this, I will start merging the PRs with breaking changes.

Release 0.67.

---

.github/workflows/dev-testing.yml

This PR isolates the workflow fix from #1146, so we can check that PR more easily.

updated dev tests so they can be dispatched manually

---

CHANGELOG.md
pyproject.toml
tests/test_ecephys/test_tools_spikeinterface.py

To the latest release. After this, we can move forward with changes like #1191 and #1117

Update to Spikeinterface latest version

---

.github/workflows/neuroconv_docker_testing.yml
tests/docker_yaml_conversion_specification_cli.py

See https://github.com/catalystneuro/neuroconv/actions/runs/13254425466

Fixed docker tests

---

pyproject.toml

Checking if the test in MacOS latest still fails with this.

Update dandi version floor

---

CHANGELOG.md
src/neuroconv/datainterfaces/ophys/tdt_fp/tdtfiberphotometrydatainterface.py
tests/test_on_data/ophys/test_fiber_photometry_interfaces.py

Added stub_test option to TDTFiberPhotometryInterface

---

.clinerules

I think adding this is also a good idea. @luiztauffer @bendichter

Add cline rule about inlining imports.

---

.github/workflows/assess-file-changes.yml

Fix security issue

---

.github/workflows/formatwise-installation-testing.yml
.github/workflows/live-service-testing.yml
.github/workflows/neuroconv_docker_testing.yml
.github/workflows/update-s3-testing-data.yml
CHANGELOG.md

With this we will be able to avoid some sudden failure when they deprecated output setting.

Fix ci deprecation warnings

---

.clinerules
CHANGELOG.md
src/neuroconv/datainterfaces/behavior/video/externalvideointerface.py
src/neuroconv/datainterfaces/behavior/video/internalvideointerface.py
tests/test_behavior/test_external_video_interface.py
tests/test_behavior/test_internal_video_interface.py

Fixes #1277
Will update conversion gallery in #1276

Added device to video interface

---

pyproject.toml

See https://github.com/zarr-developers/numcodecs/issues/721 and https://github.com/catalystneuro/roiextractors/pull/414#event-17157013465

Pin numcodecs 

---

CHANGELOG.md
src/neuroconv/datainterfaces/ecephys/basesortingextractorinterface.py
src/neuroconv/datainterfaces/ophys/basesegmentationextractorinterface.py

Fix sorting extractor setting on sorting interfaces

---

CHANGELOG.md
src/neuroconv/datainterfaces/behavior/deeplabcut/_dlc_utils.py
tests/test_on_data/behavior/test_pose_estimation_interfaces.py

Draft. From the Marie Suver conversion.

Write rate and starting time in  `DeepLabCutInterface` if timestamps are regular

---

CHANGELOG.md
docs/user_guide/nwbconverter.rst

This came from a conversion on Slack. I realize that we don't have documentation on how to set conversion options with the `NWBConverter`.

Add conversion options  with `NWBConverter`  documentation

---

CHANGELOG.md
docs/how_to/index.rst
docs/how_to/set_probe_on_recording_interfaces.rst
docs/index.rst

Should fix #635
Hey, @bendichter, I think this will be a minimal one, let me know if this covers or is what you had in mind. We can improve from this base.
https://neuroconv--1300.org.readthedocs.build/en/1300/how_to/set_probe_on_recording_interfaces.html

Probe setting how to

---

CHANGELOG.md
pyproject.toml
src/neuroconv/tools/roiextractors/roiextractors.py
src/neuroconv/tools/testing/data_interface_mixins.py
tests/test_on_data/ophys/test_imaging_interfaces.py

This was released last Friday.

Add support for latest roiextractors

---

CHANGELOG.md
src/neuroconv/datainterfaces/behavior/audio/audiointerface.py
tests/test_behavior/test_audio_interface.py

Fix AudioInterface for multi-dot filenames

---

.github/workflows/testing.yml
CHANGELOG.md
docs/conversion_examples_gallery/conftest.py
pyproject.toml
src/neuroconv/datainterfaces/behavior/sleap/sleapdatainterface.py
tests/test_on_data/behavior/test_pose_estimation_interfaces.py

Depends on https://github.com/rly/ndx-pose/pull/41

Updated to sleap-io 0.3.0

---

.gitignore

After the discussion on #1230 and the team meeting. 
We should close #1230 after this.
I don't think this needs a changelog.

Add memory bank cline to gitignore

---

pyproject.toml

Temporary pin until https://github.com/dandi/dandi-archive/pull/2383 is resolved

Fix live service tests

---

CHANGELOG.md
src/neuroconv/datainterfaces/behavior/deeplabcut/_dlc_utils.py
src/neuroconv/datainterfaces/behavior/deeplabcut/deeplabcutdatainterface.py
tests/test_on_data/behavior/test_pose_estimation_interfaces.py

Added support for renaming Skeletons with DeepLabCutInterface

---

CHANGELOG.md
pyproject.toml

Add ndx-events as a spikeglx dependency

---

src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxconverter.py

SpikeGLX SYNC channel bug fix.

---

CHANGELOG.md
docs/conversion_examples_gallery/behavior/medpc.rst

Test medpc in the conversion gallery

---

.github/workflows/dailies.yml
.github/workflows/formatwise-installation-testing.yml
CHANGELOG.md

As requested on #1380 in this comment:
https://github.com/catalystneuro/neuroconv/pull/1380#discussion_r2136052674

Add conversion gallery testing to dailies workflow

---

CHANGELOG.md
docs/conversion_examples_gallery/behavior/deeplabcut.rst
src/neuroconv/datainterfaces/behavior/deeplabcut/_dlc_utils.py
src/neuroconv/datainterfaces/behavior/deeplabcut/deeplabcutdatainterface.py
tests/test_on_data/behavior/test_pose_estimation_interfaces.py

Full Metadata support for PoseEstimation in DeepLabCutInterface

---

.github/workflows/copilot-setup-steps.yml

Fixes bug where copilot setup wouldn't completely install pre-commit which was causing the agent to timeout in #1419 
See https://github.com/catalystneuro/neuroconv/actions/runs/16007955285/job/45158875619

Fix Copilot setup

---

src/neuroconv/datainterfaces/ecephys/baserecordingextractorinterface.py
src/neuroconv/datainterfaces/ecephys/basesortingextractorinterface.py
src/neuroconv/tools/testing/data_interface_mixins.py

This will close #1346 
Plus, it fixes some other deprecations messages. 
This is an internal changes that does not need a changelog.

Fix spikeinterface imports

---

CHANGELOG.md
src/neuroconv/tools/importing.py
tests/test_minimal/test_tools/test_importing.py

Replaces:
https://github.com/catalystneuro/neuroconv/pull/1397

Fix package import check II

---

pyproject.toml

As in the title, also removing some entries from the dependency graph in pyproject. 
No changelog needed for this one

Add Alessandra to authors in pyproject.

---

docs/user_guide/adding_trials.rst

Enhance documentation for adding trials to NWB files with detailed examples
